#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 112
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_BSLASHstarttext = 1,
  anon_sym_BSLASHstartcomponent = 2,
  anon_sym_BSLASHstoptext = 3,
  anon_sym_BSLASHstopcomponent = 4,
  aux_sym_comment_token1 = 5,
  anon_sym_POUND = 6,
  anon_sym_DOLLAR = 7,
  anon_sym_PERCENT = 8,
  anon_sym_AMP = 9,
  anon_sym_CARET = 10,
  anon_sym__ = 11,
  anon_sym_LBRACE = 12,
  anon_sym_RBRACE = 13,
  anon_sym_PIPE = 14,
  anon_sym_TILDE = 15,
  anon_sym_BSLASH = 16,
  aux_sym_command_token1 = 17,
  anon_sym_LBRACK = 18,
  anon_sym_COMMA = 19,
  anon_sym_RBRACK = 20,
  anon_sym_EQ = 21,
  sym_opkey = 22,
  sym_text = 23,
  sym_optext = 24,
  sym_name = 25,
  anon_sym_LF = 26,
  sym_document = 27,
  sym_main_start = 28,
  sym_main_stop = 29,
  sym__content = 30,
  sym__opcontent = 31,
  sym__math_content = 32,
  sym_comment = 33,
  sym_escapechar = 34,
  sym_escaped = 35,
  sym_brace_group = 36,
  sym_math_group = 37,
  sym_command = 38,
  sym_optionblock = 39,
  sym__options = 40,
  sym_opval = 41,
  sym__newline = 42,
  aux_sym_document_repeat1 = 43,
  aux_sym_math_group_repeat1 = 44,
  aux_sym_command_repeat1 = 45,
  aux_sym_optionblock_repeat1 = 46,
  aux_sym_opval_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_BSLASHstarttext] = "\\starttext",
  [anon_sym_BSLASHstartcomponent] = "\\startcomponent",
  [anon_sym_BSLASHstoptext] = "\\stoptext",
  [anon_sym_BSLASHstopcomponent] = "\\stopcomponent",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_POUND] = "#",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_PERCENT] = "%",
  [anon_sym_AMP] = "&",
  [anon_sym_CARET] = "^",
  [anon_sym__] = "_",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_PIPE] = "|",
  [anon_sym_TILDE] = "~",
  [anon_sym_BSLASH] = "\\",
  [aux_sym_command_token1] = "command_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_EQ] = "=",
  [sym_opkey] = "opkey",
  [sym_text] = "text",
  [sym_optext] = "optext",
  [sym_name] = "name",
  [anon_sym_LF] = "\n",
  [sym_document] = "document",
  [sym_main_start] = "main_start",
  [sym_main_stop] = "main_stop",
  [sym__content] = "_content",
  [sym__opcontent] = "_opcontent",
  [sym__math_content] = "_math_content",
  [sym_comment] = "comment",
  [sym_escapechar] = "escapechar",
  [sym_escaped] = "escaped",
  [sym_brace_group] = "brace_group",
  [sym_math_group] = "math_group",
  [sym_command] = "command",
  [sym_optionblock] = "optionblock",
  [sym__options] = "_options",
  [sym_opval] = "opval",
  [sym__newline] = "_newline",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_math_group_repeat1] = "math_group_repeat1",
  [aux_sym_command_repeat1] = "command_repeat1",
  [aux_sym_optionblock_repeat1] = "optionblock_repeat1",
  [aux_sym_opval_repeat1] = "opval_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_BSLASHstarttext] = anon_sym_BSLASHstarttext,
  [anon_sym_BSLASHstartcomponent] = anon_sym_BSLASHstartcomponent,
  [anon_sym_BSLASHstoptext] = anon_sym_BSLASHstoptext,
  [anon_sym_BSLASHstopcomponent] = anon_sym_BSLASHstopcomponent,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym__] = anon_sym__,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [aux_sym_command_token1] = aux_sym_command_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_opkey] = sym_opkey,
  [sym_text] = sym_text,
  [sym_optext] = sym_optext,
  [sym_name] = sym_name,
  [anon_sym_LF] = anon_sym_LF,
  [sym_document] = sym_document,
  [sym_main_start] = sym_main_start,
  [sym_main_stop] = sym_main_stop,
  [sym__content] = sym__content,
  [sym__opcontent] = sym__opcontent,
  [sym__math_content] = sym__math_content,
  [sym_comment] = sym_comment,
  [sym_escapechar] = sym_escapechar,
  [sym_escaped] = sym_escaped,
  [sym_brace_group] = sym_brace_group,
  [sym_math_group] = sym_math_group,
  [sym_command] = sym_command,
  [sym_optionblock] = sym_optionblock,
  [sym__options] = sym__options,
  [sym_opval] = sym_opval,
  [sym__newline] = sym__newline,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_math_group_repeat1] = aux_sym_math_group_repeat1,
  [aux_sym_command_repeat1] = aux_sym_command_repeat1,
  [aux_sym_optionblock_repeat1] = aux_sym_optionblock_repeat1,
  [aux_sym_opval_repeat1] = aux_sym_opval_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BSLASHstarttext] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHstartcomponent] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHstoptext] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHstopcomponent] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_command_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_opkey] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_optext] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_main_start] = {
    .visible = true,
    .named = true,
  },
  [sym_main_stop] = {
    .visible = true,
    .named = true,
  },
  [sym__content] = {
    .visible = false,
    .named = true,
  },
  [sym__opcontent] = {
    .visible = false,
    .named = true,
  },
  [sym__math_content] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_escapechar] = {
    .visible = true,
    .named = true,
  },
  [sym_escaped] = {
    .visible = true,
    .named = true,
  },
  [sym_brace_group] = {
    .visible = true,
    .named = true,
  },
  [sym_math_group] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_optionblock] = {
    .visible = true,
    .named = true,
  },
  [sym__options] = {
    .visible = false,
    .named = true,
  },
  [sym_opval] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_math_group_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_command_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_optionblock_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opval_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(38);
      if (lookahead == '#') ADVANCE(45);
      if (lookahead == '$') ADVANCE(46);
      if (lookahead == '%') ADVANCE(47);
      if (lookahead == '&') ADVANCE(48);
      if (lookahead == ',') ADVANCE(60);
      if (lookahead == '=') ADVANCE(62);
      if (lookahead == '[') ADVANCE(59);
      if (lookahead == '\\') ADVANCE(56);
      if (lookahead == ']') ADVANCE(61);
      if (lookahead == '^') ADVANCE(49);
      if (lookahead == '_') ADVANCE(50);
      if (lookahead == '{') ADVANCE(51);
      if (lookahead == '|') ADVANCE(53);
      if (lookahead == '}') ADVANCE(52);
      if (lookahead == '~') ADVANCE(54);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(69);
      if (lookahead == '$') ADVANCE(46);
      if (lookahead == '%') ADVANCE(44);
      if (lookahead == '\\') ADVANCE(55);
      if (lookahead == '{') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '&' &&
          (lookahead < '[' || '_' < lookahead) &&
          (lookahead < '|' || '~' < lookahead)) ADVANCE(66);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(70);
      if (lookahead == '%') ADVANCE(43);
      if (lookahead == ',') ADVANCE(60);
      if (lookahead == '[') ADVANCE(59);
      if (lookahead == '\\') ADVANCE(55);
      if (lookahead == ']') ADVANCE(61);
      if (lookahead == '{') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(67);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(71);
      if (lookahead == '%') ADVANCE(43);
      if (lookahead == ',') ADVANCE(60);
      if (lookahead == '[') ADVANCE(59);
      if (lookahead == '\\') ADVANCE(55);
      if (lookahead == ']') ADVANCE(61);
      if (lookahead == '{') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(67);
      END_STATE();
    case 4:
      if (lookahead == ' ') SKIP(4)
      if (lookahead == ',') ADVANCE(60);
      if (lookahead == ']') ADVANCE(61);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '=' &&
          lookahead != '[') ADVANCE(64);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(58);
      if (lookahead == ']') ADVANCE(61);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != ',' &&
          lookahead != '=' &&
          lookahead != '[') ADVANCE(64);
      END_STATE();
    case 6:
      if (lookahead == '#') ADVANCE(45);
      if (lookahead == '$') ADVANCE(46);
      if (lookahead == '%') ADVANCE(47);
      if (lookahead == '&') ADVANCE(48);
      if (lookahead == '\\') ADVANCE(55);
      if (lookahead == '^') ADVANCE(49);
      if (lookahead == '_') ADVANCE(50);
      if (lookahead == '{') ADVANCE(51);
      if (lookahead == '|') ADVANCE(53);
      if (lookahead == '}') ADVANCE(52);
      if (lookahead == '~') ADVANCE(54);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(27);
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(20);
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(23);
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 'm') ADVANCE(25);
      END_STATE();
    case 15:
      if (lookahead == 'm') ADVANCE(26);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(31);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(32);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 24:
      if (lookahead == 'p') ADVANCE(8);
      END_STATE();
    case 25:
      if (lookahead == 'p') ADVANCE(21);
      END_STATE();
    case 26:
      if (lookahead == 'p') ADVANCE(22);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(33);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(7);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 34:
      if (lookahead == 'x') ADVANCE(29);
      END_STATE();
    case 35:
      if (lookahead == 'x') ADVANCE(30);
      END_STATE();
    case 36:
      if (eof) ADVANCE(38);
      if (lookahead == '\n') ADVANCE(69);
      if (lookahead == '$') ADVANCE(46);
      if (lookahead == '%') ADVANCE(44);
      if (lookahead == '[') ADVANCE(59);
      if (lookahead == '\\') ADVANCE(56);
      if (lookahead == '{') ADVANCE(51);
      if (lookahead == '}') ADVANCE(52);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != '&' &&
          (lookahead < ']' || '_' < lookahead) &&
          (lookahead < '|' || '~' < lookahead)) ADVANCE(66);
      END_STATE();
    case 37:
      if (eof) ADVANCE(38);
      if (lookahead == '\n') ADVANCE(71);
      if (lookahead == '$') ADVANCE(46);
      if (lookahead == '%') ADVANCE(44);
      if (lookahead == '[') ADVANCE(59);
      if (lookahead == '\\') ADVANCE(56);
      if (lookahead == '{') ADVANCE(51);
      if (lookahead == '}') ADVANCE(52);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '&' &&
          (lookahead < ']' || '_' < lookahead) &&
          (lookahead < '|' || '~' < lookahead)) ADVANCE(66);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_BSLASHstarttext);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_BSLASHstartcomponent);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_BSLASHstoptext);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_BSLASHstopcomponent);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\n') ADVANCE(67);
      if (lookahead == ',' ||
          ('[' <= lookahead && lookahead <= ']') ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(44);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == 's') ADVANCE(28);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_command_token1);
      if (lookahead == '\n') ADVANCE(71);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_command_token1);
      if (lookahead == ' ') ADVANCE(58);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r') ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_opkey);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != ',' &&
          lookahead != '=' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(64);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_opkey);
      if (lookahead != 0 &&
          lookahead != ' ' &&
          lookahead != ',' &&
          lookahead != '=' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(69);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0 &&
          (lookahead < '$' || '&' < lookahead) &&
          (lookahead < '[' || '_' < lookahead) &&
          (lookahead < '{' || '~' < lookahead)) ADVANCE(66);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          (lookahead < '$' || '&' < lookahead) &&
          (lookahead < '[' || '_' < lookahead) &&
          (lookahead < '{' || '~' < lookahead)) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_optext);
      if (lookahead != 0 &&
          lookahead != ',' &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(69);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(65);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(71);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(57);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 36},
  [2] = {.lex_state = 36},
  [3] = {.lex_state = 36},
  [4] = {.lex_state = 36},
  [5] = {.lex_state = 36},
  [6] = {.lex_state = 36},
  [7] = {.lex_state = 36},
  [8] = {.lex_state = 36},
  [9] = {.lex_state = 36},
  [10] = {.lex_state = 36},
  [11] = {.lex_state = 36},
  [12] = {.lex_state = 36},
  [13] = {.lex_state = 37},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 37},
  [16] = {.lex_state = 37},
  [17] = {.lex_state = 37},
  [18] = {.lex_state = 37},
  [19] = {.lex_state = 37},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 36},
  [23] = {.lex_state = 36},
  [24] = {.lex_state = 36},
  [25] = {.lex_state = 37},
  [26] = {.lex_state = 37},
  [27] = {.lex_state = 37},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 37},
  [30] = {.lex_state = 36},
  [31] = {.lex_state = 37},
  [32] = {.lex_state = 37},
  [33] = {.lex_state = 37},
  [34] = {.lex_state = 37},
  [35] = {.lex_state = 37},
  [36] = {.lex_state = 6},
  [37] = {.lex_state = 37},
  [38] = {.lex_state = 6},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 6},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 36},
  [46] = {.lex_state = 36},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 36},
  [49] = {.lex_state = 36},
  [50] = {.lex_state = 36},
  [51] = {.lex_state = 36},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 36},
  [54] = {.lex_state = 36},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 36},
  [57] = {.lex_state = 36},
  [58] = {.lex_state = 36},
  [59] = {.lex_state = 36},
  [60] = {.lex_state = 36},
  [61] = {.lex_state = 36},
  [62] = {.lex_state = 36},
  [63] = {.lex_state = 36},
  [64] = {.lex_state = 36},
  [65] = {.lex_state = 36},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 3},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 2},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 4},
  [84] = {.lex_state = 4},
  [85] = {.lex_state = 5},
  [86] = {.lex_state = 5},
  [87] = {.lex_state = 5},
  [88] = {.lex_state = 4},
  [89] = {.lex_state = 5},
  [90] = {.lex_state = 5},
  [91] = {.lex_state = 5},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 5},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 4},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_BSLASHstarttext] = ACTIONS(1),
    [anon_sym_BSLASHstartcomponent] = ACTIONS(1),
    [anon_sym_BSLASHstoptext] = ACTIONS(1),
    [anon_sym_BSLASHstopcomponent] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(108),
    [sym_main_start] = STATE(9),
    [sym_main_stop] = STATE(9),
    [sym__content] = STATE(9),
    [sym_comment] = STATE(9),
    [sym_escaped] = STATE(9),
    [sym_brace_group] = STATE(9),
    [sym_math_group] = STATE(9),
    [sym_command] = STATE(9),
    [sym__newline] = STATE(9),
    [aux_sym_document_repeat1] = STATE(9),
    [anon_sym_BSLASHstarttext] = ACTIONS(3),
    [anon_sym_BSLASHstartcomponent] = ACTIONS(3),
    [anon_sym_BSLASHstoptext] = ACTIONS(5),
    [anon_sym_BSLASHstopcomponent] = ACTIONS(5),
    [aux_sym_comment_token1] = ACTIONS(7),
    [anon_sym_DOLLAR] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_BSLASH] = ACTIONS(13),
    [sym_text] = ACTIONS(15),
    [anon_sym_LF] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(23), 1,
      anon_sym_DOLLAR,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    ACTIONS(29), 1,
      anon_sym_BSLASH,
    ACTIONS(17), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(19), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(31), 2,
      sym_text,
      anon_sym_LF,
    STATE(5), 10,
      sym_main_start,
      sym_main_stop,
      sym__content,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_math_group,
      sym_command,
      sym__newline,
      aux_sym_document_repeat1,
  [40] = 9,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(23), 1,
      anon_sym_DOLLAR,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      anon_sym_BSLASH,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(19), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(35), 2,
      sym_text,
      anon_sym_LF,
    STATE(8), 10,
      sym_main_start,
      sym_main_stop,
      sym__content,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_math_group,
      sym_command,
      sym__newline,
      aux_sym_document_repeat1,
  [80] = 9,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    ACTIONS(45), 1,
      aux_sym_comment_token1,
    ACTIONS(48), 1,
      anon_sym_DOLLAR,
    ACTIONS(51), 1,
      anon_sym_LBRACE,
    ACTIONS(54), 1,
      anon_sym_BSLASH,
    ACTIONS(39), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(42), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(57), 2,
      sym_text,
      anon_sym_LF,
    STATE(4), 10,
      sym_main_start,
      sym_main_stop,
      sym__content,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_math_group,
      sym_command,
      sym__newline,
      aux_sym_document_repeat1,
  [120] = 9,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(23), 1,
      anon_sym_DOLLAR,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      anon_sym_BSLASH,
    ACTIONS(60), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(19), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(62), 2,
      sym_text,
      anon_sym_LF,
    STATE(10), 10,
      sym_main_start,
      sym_main_stop,
      sym__content,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_math_group,
      sym_command,
      sym__newline,
      aux_sym_document_repeat1,
  [160] = 9,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(23), 1,
      anon_sym_DOLLAR,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      anon_sym_BSLASH,
    ACTIONS(64), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(19), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(66), 2,
      sym_text,
      anon_sym_LF,
    STATE(12), 10,
      sym_main_start,
      sym_main_stop,
      sym__content,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_math_group,
      sym_command,
      sym__newline,
      aux_sym_document_repeat1,
  [200] = 9,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(23), 1,
      anon_sym_DOLLAR,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      anon_sym_BSLASH,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(19), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(70), 2,
      sym_text,
      anon_sym_LF,
    STATE(11), 10,
      sym_main_start,
      sym_main_stop,
      sym__content,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_math_group,
      sym_command,
      sym__newline,
      aux_sym_document_repeat1,
  [240] = 9,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(23), 1,
      anon_sym_DOLLAR,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      anon_sym_BSLASH,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(19), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(62), 2,
      sym_text,
      anon_sym_LF,
    STATE(10), 10,
      sym_main_start,
      sym_main_stop,
      sym__content,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_math_group,
      sym_command,
      sym__newline,
      aux_sym_document_repeat1,
  [280] = 9,
    ACTIONS(7), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      anon_sym_DOLLAR,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_BSLASH,
    ACTIONS(74), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(5), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(76), 2,
      sym_text,
      anon_sym_LF,
    STATE(4), 10,
      sym_main_start,
      sym_main_stop,
      sym__content,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_math_group,
      sym_command,
      sym__newline,
      aux_sym_document_repeat1,
  [320] = 9,
    ACTIONS(84), 1,
      aux_sym_comment_token1,
    ACTIONS(87), 1,
      anon_sym_DOLLAR,
    ACTIONS(90), 1,
      anon_sym_LBRACE,
    ACTIONS(93), 1,
      anon_sym_RBRACE,
    ACTIONS(95), 1,
      anon_sym_BSLASH,
    ACTIONS(78), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(81), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(98), 2,
      sym_text,
      anon_sym_LF,
    STATE(10), 10,
      sym_main_start,
      sym_main_stop,
      sym__content,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_math_group,
      sym_command,
      sym__newline,
      aux_sym_document_repeat1,
  [360] = 9,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(23), 1,
      anon_sym_DOLLAR,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      anon_sym_BSLASH,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(19), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(62), 2,
      sym_text,
      anon_sym_LF,
    STATE(10), 10,
      sym_main_start,
      sym_main_stop,
      sym__content,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_math_group,
      sym_command,
      sym__newline,
      aux_sym_document_repeat1,
  [400] = 9,
    ACTIONS(21), 1,
      aux_sym_comment_token1,
    ACTIONS(23), 1,
      anon_sym_DOLLAR,
    ACTIONS(25), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      anon_sym_BSLASH,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(19), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(62), 2,
      sym_text,
      anon_sym_LF,
    STATE(10), 10,
      sym_main_start,
      sym_main_stop,
      sym__content,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_math_group,
      sym_command,
      sym__newline,
      aux_sym_document_repeat1,
  [440] = 4,
    ACTIONS(107), 1,
      aux_sym_command_token1,
    ACTIONS(110), 1,
      anon_sym_LBRACK,
    STATE(13), 2,
      sym_optionblock,
      aux_sym_command_repeat1,
    ACTIONS(105), 11,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [464] = 8,
    ACTIONS(113), 1,
      aux_sym_comment_token1,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      anon_sym_BSLASH,
    ACTIONS(121), 1,
      sym_optext,
    ACTIONS(123), 1,
      anon_sym_LF,
    STATE(103), 1,
      sym_opval,
    ACTIONS(119), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    STATE(20), 7,
      sym__opcontent,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_command,
      sym__newline,
      aux_sym_opval_repeat1,
  [496] = 5,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
    ACTIONS(127), 1,
      aux_sym_command_token1,
    ACTIONS(130), 1,
      anon_sym_LBRACK,
    STATE(15), 2,
      sym_optionblock,
      aux_sym_command_repeat1,
    ACTIONS(105), 10,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [522] = 5,
    ACTIONS(133), 1,
      ts_builtin_sym_end,
    ACTIONS(137), 1,
      aux_sym_command_token1,
    ACTIONS(139), 1,
      anon_sym_LBRACK,
    STATE(19), 2,
      sym_optionblock,
      aux_sym_command_repeat1,
    ACTIONS(135), 10,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [548] = 4,
    ACTIONS(141), 1,
      aux_sym_command_token1,
    ACTIONS(143), 1,
      anon_sym_LBRACK,
    STATE(18), 2,
      sym_optionblock,
      aux_sym_command_repeat1,
    ACTIONS(135), 11,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [572] = 4,
    ACTIONS(143), 1,
      anon_sym_LBRACK,
    ACTIONS(147), 1,
      aux_sym_command_token1,
    STATE(13), 2,
      sym_optionblock,
      aux_sym_command_repeat1,
    ACTIONS(145), 11,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [596] = 5,
    ACTIONS(139), 1,
      anon_sym_LBRACK,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
    ACTIONS(151), 1,
      aux_sym_command_token1,
    STATE(15), 2,
      sym_optionblock,
      aux_sym_command_repeat1,
    ACTIONS(145), 10,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [622] = 7,
    ACTIONS(113), 1,
      aux_sym_comment_token1,
    ACTIONS(115), 1,
      anon_sym_LBRACE,
    ACTIONS(117), 1,
      anon_sym_BSLASH,
    ACTIONS(155), 1,
      sym_optext,
    ACTIONS(157), 1,
      anon_sym_LF,
    ACTIONS(153), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    STATE(21), 7,
      sym__opcontent,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_command,
      sym__newline,
      aux_sym_opval_repeat1,
  [651] = 7,
    ACTIONS(159), 1,
      aux_sym_comment_token1,
    ACTIONS(162), 1,
      anon_sym_LBRACE,
    ACTIONS(165), 1,
      anon_sym_BSLASH,
    ACTIONS(170), 1,
      sym_optext,
    ACTIONS(173), 1,
      anon_sym_LF,
    ACTIONS(168), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    STATE(21), 7,
      sym__opcontent,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_command,
      sym__newline,
      aux_sym_opval_repeat1,
  [680] = 4,
    ACTIONS(139), 1,
      anon_sym_LBRACK,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
    STATE(25), 1,
      sym_optionblock,
    ACTIONS(145), 10,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [702] = 3,
    ACTIONS(143), 1,
      anon_sym_LBRACK,
    STATE(29), 1,
      sym_optionblock,
    ACTIONS(176), 11,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [722] = 3,
    ACTIONS(143), 1,
      anon_sym_LBRACK,
    STATE(29), 1,
      sym_optionblock,
    ACTIONS(145), 11,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [742] = 2,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
    ACTIONS(105), 12,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      aux_sym_command_token1,
      anon_sym_LBRACK,
      sym_text,
      anon_sym_LF,
  [760] = 1,
    ACTIONS(178), 13,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      aux_sym_command_token1,
      anon_sym_LBRACK,
      sym_text,
      anon_sym_LF,
  [776] = 2,
    ACTIONS(180), 1,
      ts_builtin_sym_end,
    ACTIONS(182), 12,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      aux_sym_command_token1,
      anon_sym_LBRACK,
      sym_text,
      anon_sym_LF,
  [794] = 3,
    ACTIONS(186), 1,
      sym_name,
    STATE(76), 1,
      sym_escapechar,
    ACTIONS(184), 11,
      anon_sym_POUND,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_AMP,
      anon_sym_CARET,
      anon_sym__,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_BSLASH,
  [814] = 1,
    ACTIONS(105), 13,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      aux_sym_command_token1,
      anon_sym_LBRACK,
      sym_text,
      anon_sym_LF,
  [830] = 4,
    ACTIONS(139), 1,
      anon_sym_LBRACK,
    ACTIONS(188), 1,
      ts_builtin_sym_end,
    STATE(25), 1,
      sym_optionblock,
    ACTIONS(176), 10,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [852] = 1,
    ACTIONS(182), 13,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      aux_sym_command_token1,
      anon_sym_LBRACK,
      sym_text,
      anon_sym_LF,
  [868] = 2,
    ACTIONS(190), 1,
      ts_builtin_sym_end,
    ACTIONS(192), 12,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      aux_sym_command_token1,
      anon_sym_LBRACK,
      sym_text,
      anon_sym_LF,
  [886] = 1,
    ACTIONS(194), 13,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      aux_sym_command_token1,
      anon_sym_LBRACK,
      sym_text,
      anon_sym_LF,
  [902] = 2,
    ACTIONS(196), 1,
      ts_builtin_sym_end,
    ACTIONS(194), 12,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      aux_sym_command_token1,
      anon_sym_LBRACK,
      sym_text,
      anon_sym_LF,
  [920] = 1,
    ACTIONS(192), 13,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      aux_sym_command_token1,
      anon_sym_LBRACK,
      sym_text,
      anon_sym_LF,
  [936] = 3,
    ACTIONS(200), 1,
      sym_name,
    STATE(50), 1,
      sym_escapechar,
    ACTIONS(198), 11,
      anon_sym_POUND,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_AMP,
      anon_sym_CARET,
      anon_sym__,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_BSLASH,
  [956] = 2,
    ACTIONS(202), 1,
      ts_builtin_sym_end,
    ACTIONS(178), 12,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      aux_sym_command_token1,
      anon_sym_LBRACK,
      sym_text,
      anon_sym_LF,
  [974] = 3,
    ACTIONS(206), 1,
      sym_name,
    STATE(45), 1,
      sym_escapechar,
    ACTIONS(204), 11,
      anon_sym_POUND,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_AMP,
      anon_sym_CARET,
      anon_sym__,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_BSLASH,
  [994] = 6,
    ACTIONS(208), 1,
      aux_sym_comment_token1,
    ACTIONS(210), 1,
      anon_sym_DOLLAR,
    ACTIONS(212), 1,
      anon_sym_LBRACE,
    ACTIONS(214), 1,
      anon_sym_BSLASH,
    ACTIONS(216), 2,
      sym_text,
      anon_sym_LF,
    STATE(42), 6,
      sym__math_content,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym__newline,
      aux_sym_math_group_repeat1,
  [1019] = 2,
    STATE(79), 1,
      sym_escapechar,
    ACTIONS(218), 11,
      anon_sym_POUND,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_AMP,
      anon_sym_CARET,
      anon_sym__,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_BSLASH,
  [1036] = 6,
    ACTIONS(208), 1,
      aux_sym_comment_token1,
    ACTIONS(212), 1,
      anon_sym_LBRACE,
    ACTIONS(214), 1,
      anon_sym_BSLASH,
    ACTIONS(220), 1,
      anon_sym_DOLLAR,
    ACTIONS(222), 2,
      sym_text,
      anon_sym_LF,
    STATE(43), 6,
      sym__math_content,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym__newline,
      aux_sym_math_group_repeat1,
  [1061] = 6,
    ACTIONS(208), 1,
      aux_sym_comment_token1,
    ACTIONS(212), 1,
      anon_sym_LBRACE,
    ACTIONS(214), 1,
      anon_sym_BSLASH,
    ACTIONS(224), 1,
      anon_sym_DOLLAR,
    ACTIONS(226), 2,
      sym_text,
      anon_sym_LF,
    STATE(44), 6,
      sym__math_content,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym__newline,
      aux_sym_math_group_repeat1,
  [1086] = 6,
    ACTIONS(208), 1,
      aux_sym_comment_token1,
    ACTIONS(212), 1,
      anon_sym_LBRACE,
    ACTIONS(214), 1,
      anon_sym_BSLASH,
    ACTIONS(228), 1,
      anon_sym_DOLLAR,
    ACTIONS(226), 2,
      sym_text,
      anon_sym_LF,
    STATE(44), 6,
      sym__math_content,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym__newline,
      aux_sym_math_group_repeat1,
  [1111] = 6,
    ACTIONS(230), 1,
      aux_sym_comment_token1,
    ACTIONS(233), 1,
      anon_sym_DOLLAR,
    ACTIONS(235), 1,
      anon_sym_LBRACE,
    ACTIONS(238), 1,
      anon_sym_BSLASH,
    ACTIONS(241), 2,
      sym_text,
      anon_sym_LF,
    STATE(44), 6,
      sym__math_content,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym__newline,
      aux_sym_math_group_repeat1,
  [1136] = 2,
    ACTIONS(244), 1,
      ts_builtin_sym_end,
    ACTIONS(246), 10,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [1152] = 2,
    ACTIONS(248), 1,
      ts_builtin_sym_end,
    ACTIONS(250), 10,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [1168] = 4,
    ACTIONS(252), 1,
      aux_sym_command_token1,
    ACTIONS(255), 1,
      anon_sym_LBRACK,
    STATE(47), 2,
      sym_optionblock,
      aux_sym_command_repeat1,
    ACTIONS(105), 7,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_optext,
      anon_sym_LF,
  [1188] = 1,
    ACTIONS(258), 11,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [1202] = 1,
    ACTIONS(260), 11,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [1216] = 1,
    ACTIONS(246), 11,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [1230] = 1,
    ACTIONS(262), 11,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [1244] = 4,
    ACTIONS(264), 1,
      aux_sym_command_token1,
    ACTIONS(266), 1,
      anon_sym_LBRACK,
    STATE(55), 2,
      sym_optionblock,
      aux_sym_command_repeat1,
    ACTIONS(135), 7,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_optext,
      anon_sym_LF,
  [1264] = 1,
    ACTIONS(268), 11,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [1278] = 1,
    ACTIONS(270), 11,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [1292] = 4,
    ACTIONS(266), 1,
      anon_sym_LBRACK,
    ACTIONS(272), 1,
      aux_sym_command_token1,
    STATE(47), 2,
      sym_optionblock,
      aux_sym_command_repeat1,
    ACTIONS(145), 7,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_optext,
      anon_sym_LF,
  [1312] = 1,
    ACTIONS(250), 11,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [1326] = 1,
    ACTIONS(274), 11,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [1340] = 2,
    ACTIONS(276), 1,
      ts_builtin_sym_end,
    ACTIONS(260), 10,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [1356] = 2,
    ACTIONS(278), 1,
      ts_builtin_sym_end,
    ACTIONS(258), 10,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [1372] = 2,
    ACTIONS(280), 1,
      ts_builtin_sym_end,
    ACTIONS(282), 10,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [1388] = 2,
    ACTIONS(284), 1,
      ts_builtin_sym_end,
    ACTIONS(274), 10,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [1404] = 1,
    ACTIONS(282), 11,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [1418] = 2,
    ACTIONS(286), 1,
      ts_builtin_sym_end,
    ACTIONS(268), 10,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [1434] = 2,
    ACTIONS(288), 1,
      ts_builtin_sym_end,
    ACTIONS(270), 10,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [1450] = 2,
    ACTIONS(290), 1,
      ts_builtin_sym_end,
    ACTIONS(262), 10,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [1466] = 1,
    ACTIONS(182), 9,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      aux_sym_command_token1,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_optext,
      anon_sym_LF,
  [1478] = 4,
    ACTIONS(188), 1,
      anon_sym_LF,
    ACTIONS(266), 1,
      anon_sym_LBRACK,
    STATE(71), 1,
      sym_optionblock,
    ACTIONS(176), 6,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_optext,
  [1496] = 4,
    ACTIONS(149), 1,
      anon_sym_LF,
    ACTIONS(266), 1,
      anon_sym_LBRACK,
    STATE(71), 1,
      sym_optionblock,
    ACTIONS(145), 6,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_optext,
  [1514] = 1,
    ACTIONS(192), 9,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      aux_sym_command_token1,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_optext,
      anon_sym_LF,
  [1526] = 1,
    ACTIONS(194), 9,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      aux_sym_command_token1,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_optext,
      anon_sym_LF,
  [1538] = 1,
    ACTIONS(105), 9,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      aux_sym_command_token1,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_optext,
      anon_sym_LF,
  [1550] = 1,
    ACTIONS(178), 9,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      aux_sym_command_token1,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_optext,
      anon_sym_LF,
  [1562] = 2,
    ACTIONS(288), 1,
      anon_sym_LF,
    ACTIONS(270), 6,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_optext,
  [1574] = 2,
    ACTIONS(248), 1,
      anon_sym_LF,
    ACTIONS(250), 6,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_optext,
  [1586] = 2,
    ACTIONS(286), 1,
      anon_sym_LF,
    ACTIONS(268), 6,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_optext,
  [1598] = 2,
    ACTIONS(244), 1,
      anon_sym_LF,
    ACTIONS(246), 6,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_optext,
  [1610] = 2,
    ACTIONS(280), 1,
      anon_sym_LF,
    ACTIONS(282), 6,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_optext,
  [1622] = 1,
    ACTIONS(282), 6,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [1631] = 1,
    ACTIONS(246), 6,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [1640] = 1,
    ACTIONS(268), 6,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [1649] = 1,
    ACTIONS(270), 6,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [1658] = 1,
    ACTIONS(250), 6,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      sym_text,
      anon_sym_LF,
  [1667] = 4,
    ACTIONS(292), 1,
      anon_sym_COMMA,
    ACTIONS(294), 1,
      anon_sym_RBRACK,
    ACTIONS(296), 1,
      sym_opkey,
    STATE(93), 1,
      sym__options,
  [1680] = 4,
    ACTIONS(296), 1,
      sym_opkey,
    ACTIONS(298), 1,
      anon_sym_COMMA,
    ACTIONS(300), 1,
      anon_sym_RBRACK,
    STATE(96), 1,
      sym__options,
  [1693] = 4,
    ACTIONS(302), 1,
      aux_sym_command_token1,
    ACTIONS(304), 1,
      anon_sym_RBRACK,
    ACTIONS(306), 1,
      sym_opkey,
    STATE(105), 1,
      sym__options,
  [1706] = 4,
    ACTIONS(302), 1,
      aux_sym_command_token1,
    ACTIONS(306), 1,
      sym_opkey,
    ACTIONS(308), 1,
      anon_sym_RBRACK,
    STATE(105), 1,
      sym__options,
  [1719] = 4,
    ACTIONS(302), 1,
      aux_sym_command_token1,
    ACTIONS(306), 1,
      sym_opkey,
    ACTIONS(310), 1,
      anon_sym_RBRACK,
    STATE(105), 1,
      sym__options,
  [1732] = 4,
    ACTIONS(296), 1,
      sym_opkey,
    ACTIONS(312), 1,
      anon_sym_COMMA,
    ACTIONS(314), 1,
      anon_sym_RBRACK,
    STATE(98), 1,
      sym__options,
  [1745] = 4,
    ACTIONS(302), 1,
      aux_sym_command_token1,
    ACTIONS(306), 1,
      sym_opkey,
    ACTIONS(316), 1,
      anon_sym_RBRACK,
    STATE(105), 1,
      sym__options,
  [1758] = 4,
    ACTIONS(302), 1,
      aux_sym_command_token1,
    ACTIONS(306), 1,
      sym_opkey,
    ACTIONS(318), 1,
      anon_sym_RBRACK,
    STATE(105), 1,
      sym__options,
  [1771] = 4,
    ACTIONS(302), 1,
      aux_sym_command_token1,
    ACTIONS(306), 1,
      sym_opkey,
    ACTIONS(320), 1,
      anon_sym_RBRACK,
    STATE(105), 1,
      sym__options,
  [1784] = 3,
    ACTIONS(322), 1,
      anon_sym_COMMA,
    ACTIONS(324), 1,
      anon_sym_RBRACK,
    STATE(100), 1,
      aux_sym_optionblock_repeat1,
  [1794] = 3,
    ACTIONS(326), 1,
      anon_sym_COMMA,
    ACTIONS(328), 1,
      anon_sym_RBRACK,
    STATE(95), 1,
      aux_sym_optionblock_repeat1,
  [1804] = 3,
    ACTIONS(302), 1,
      aux_sym_command_token1,
    ACTIONS(306), 1,
      sym_opkey,
    STATE(105), 1,
      sym__options,
  [1814] = 3,
    ACTIONS(330), 1,
      anon_sym_COMMA,
    ACTIONS(332), 1,
      anon_sym_RBRACK,
    STATE(100), 1,
      aux_sym_optionblock_repeat1,
  [1824] = 3,
    ACTIONS(334), 1,
      anon_sym_COMMA,
    ACTIONS(336), 1,
      anon_sym_RBRACK,
    STATE(92), 1,
      aux_sym_optionblock_repeat1,
  [1834] = 2,
    ACTIONS(340), 1,
      anon_sym_EQ,
    ACTIONS(338), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1842] = 3,
    ACTIONS(342), 1,
      anon_sym_COMMA,
    ACTIONS(344), 1,
      anon_sym_RBRACK,
    STATE(99), 1,
      aux_sym_optionblock_repeat1,
  [1852] = 3,
    ACTIONS(346), 1,
      anon_sym_COMMA,
    ACTIONS(348), 1,
      anon_sym_RBRACK,
    STATE(100), 1,
      aux_sym_optionblock_repeat1,
  [1862] = 3,
    ACTIONS(350), 1,
      anon_sym_COMMA,
    ACTIONS(353), 1,
      anon_sym_RBRACK,
    STATE(100), 1,
      aux_sym_optionblock_repeat1,
  [1872] = 2,
    ACTIONS(355), 1,
      anon_sym_LBRACK,
    STATE(29), 1,
      sym_optionblock,
  [1879] = 2,
    ACTIONS(357), 1,
      anon_sym_LBRACK,
    STATE(25), 1,
      sym_optionblock,
  [1886] = 1,
    ACTIONS(359), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1891] = 2,
    ACTIONS(296), 1,
      sym_opkey,
    STATE(107), 1,
      sym__options,
  [1898] = 1,
    ACTIONS(353), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1903] = 2,
    ACTIONS(361), 1,
      anon_sym_LBRACK,
    STATE(71), 1,
      sym_optionblock,
  [1910] = 1,
    ACTIONS(363), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1915] = 1,
    ACTIONS(365), 1,
      ts_builtin_sym_end,
  [1919] = 1,
    ACTIONS(328), 1,
      anon_sym_RBRACK,
  [1923] = 1,
    ACTIONS(344), 1,
      anon_sym_RBRACK,
  [1927] = 1,
    ACTIONS(336), 1,
      anon_sym_RBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 80,
  [SMALL_STATE(5)] = 120,
  [SMALL_STATE(6)] = 160,
  [SMALL_STATE(7)] = 200,
  [SMALL_STATE(8)] = 240,
  [SMALL_STATE(9)] = 280,
  [SMALL_STATE(10)] = 320,
  [SMALL_STATE(11)] = 360,
  [SMALL_STATE(12)] = 400,
  [SMALL_STATE(13)] = 440,
  [SMALL_STATE(14)] = 464,
  [SMALL_STATE(15)] = 496,
  [SMALL_STATE(16)] = 522,
  [SMALL_STATE(17)] = 548,
  [SMALL_STATE(18)] = 572,
  [SMALL_STATE(19)] = 596,
  [SMALL_STATE(20)] = 622,
  [SMALL_STATE(21)] = 651,
  [SMALL_STATE(22)] = 680,
  [SMALL_STATE(23)] = 702,
  [SMALL_STATE(24)] = 722,
  [SMALL_STATE(25)] = 742,
  [SMALL_STATE(26)] = 760,
  [SMALL_STATE(27)] = 776,
  [SMALL_STATE(28)] = 794,
  [SMALL_STATE(29)] = 814,
  [SMALL_STATE(30)] = 830,
  [SMALL_STATE(31)] = 852,
  [SMALL_STATE(32)] = 868,
  [SMALL_STATE(33)] = 886,
  [SMALL_STATE(34)] = 902,
  [SMALL_STATE(35)] = 920,
  [SMALL_STATE(36)] = 936,
  [SMALL_STATE(37)] = 956,
  [SMALL_STATE(38)] = 974,
  [SMALL_STATE(39)] = 994,
  [SMALL_STATE(40)] = 1019,
  [SMALL_STATE(41)] = 1036,
  [SMALL_STATE(42)] = 1061,
  [SMALL_STATE(43)] = 1086,
  [SMALL_STATE(44)] = 1111,
  [SMALL_STATE(45)] = 1136,
  [SMALL_STATE(46)] = 1152,
  [SMALL_STATE(47)] = 1168,
  [SMALL_STATE(48)] = 1188,
  [SMALL_STATE(49)] = 1202,
  [SMALL_STATE(50)] = 1216,
  [SMALL_STATE(51)] = 1230,
  [SMALL_STATE(52)] = 1244,
  [SMALL_STATE(53)] = 1264,
  [SMALL_STATE(54)] = 1278,
  [SMALL_STATE(55)] = 1292,
  [SMALL_STATE(56)] = 1312,
  [SMALL_STATE(57)] = 1326,
  [SMALL_STATE(58)] = 1340,
  [SMALL_STATE(59)] = 1356,
  [SMALL_STATE(60)] = 1372,
  [SMALL_STATE(61)] = 1388,
  [SMALL_STATE(62)] = 1404,
  [SMALL_STATE(63)] = 1418,
  [SMALL_STATE(64)] = 1434,
  [SMALL_STATE(65)] = 1450,
  [SMALL_STATE(66)] = 1466,
  [SMALL_STATE(67)] = 1478,
  [SMALL_STATE(68)] = 1496,
  [SMALL_STATE(69)] = 1514,
  [SMALL_STATE(70)] = 1526,
  [SMALL_STATE(71)] = 1538,
  [SMALL_STATE(72)] = 1550,
  [SMALL_STATE(73)] = 1562,
  [SMALL_STATE(74)] = 1574,
  [SMALL_STATE(75)] = 1586,
  [SMALL_STATE(76)] = 1598,
  [SMALL_STATE(77)] = 1610,
  [SMALL_STATE(78)] = 1622,
  [SMALL_STATE(79)] = 1631,
  [SMALL_STATE(80)] = 1640,
  [SMALL_STATE(81)] = 1649,
  [SMALL_STATE(82)] = 1658,
  [SMALL_STATE(83)] = 1667,
  [SMALL_STATE(84)] = 1680,
  [SMALL_STATE(85)] = 1693,
  [SMALL_STATE(86)] = 1706,
  [SMALL_STATE(87)] = 1719,
  [SMALL_STATE(88)] = 1732,
  [SMALL_STATE(89)] = 1745,
  [SMALL_STATE(90)] = 1758,
  [SMALL_STATE(91)] = 1771,
  [SMALL_STATE(92)] = 1784,
  [SMALL_STATE(93)] = 1794,
  [SMALL_STATE(94)] = 1804,
  [SMALL_STATE(95)] = 1814,
  [SMALL_STATE(96)] = 1824,
  [SMALL_STATE(97)] = 1834,
  [SMALL_STATE(98)] = 1842,
  [SMALL_STATE(99)] = 1852,
  [SMALL_STATE(100)] = 1862,
  [SMALL_STATE(101)] = 1872,
  [SMALL_STATE(102)] = 1879,
  [SMALL_STATE(103)] = 1886,
  [SMALL_STATE(104)] = 1891,
  [SMALL_STATE(105)] = 1898,
  [SMALL_STATE(106)] = 1903,
  [SMALL_STATE(107)] = 1910,
  [SMALL_STATE(108)] = 1915,
  [SMALL_STATE(109)] = 1919,
  [SMALL_STATE(110)] = 1923,
  [SMALL_STATE(111)] = 1927,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(59),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(58),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(46),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(41),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(6),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(38),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(4),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [62] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(48),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(49),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(56),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(39),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(2),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2),
  [95] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(36),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(10),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2),
  [107] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(101),
  [110] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(83),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__options, 2),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2),
  [127] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(102),
  [130] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(84),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 3),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 3),
  [151] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_opval, 1),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [159] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_opval_repeat1, 2), SHIFT_REPEAT(74),
  [162] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_opval_repeat1, 2), SHIFT_REPEAT(3),
  [165] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_opval_repeat1, 2), SHIFT_REPEAT(28),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_opval_repeat1, 2),
  [170] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_opval_repeat1, 2), SHIFT_REPEAT(21),
  [173] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_opval_repeat1, 2), SHIFT_REPEAT(21),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 4),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_optionblock, 4),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optionblock, 2),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_optionblock, 2),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 4),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optionblock, 3),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_optionblock, 3),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_optionblock, 5),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optionblock, 5),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optionblock, 4),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [208] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [210] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [212] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [214] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [224] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [230] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_math_group_repeat1, 2), SHIFT_REPEAT(82),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_math_group_repeat1, 2),
  [235] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_math_group_repeat1, 2), SHIFT_REPEAT(7),
  [238] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_math_group_repeat1, 2), SHIFT_REPEAT(40),
  [241] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_math_group_repeat1, 2), SHIFT_REPEAT(44),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escaped, 2),
  [246] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escaped, 2),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1),
  [252] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(106),
  [255] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(88),
  [258] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_main_start, 1),
  [260] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_main_stop, 1),
  [262] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_group, 2),
  [264] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [266] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [268] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escapechar, 1),
  [270] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_group, 2),
  [272] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [274] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_group, 3),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_main_stop, 1),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_main_start, 1),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_brace_group, 3),
  [282] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_group, 3),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_group, 3),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escapechar, 1),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_brace_group, 2),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_math_group, 2),
  [292] = {.entry = {.count = 1, .reusable = false}}, SHIFT(109),
  [294] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [298] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [300] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [302] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [304] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [306] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [308] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [310] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [312] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [314] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [316] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [318] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [320] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [338] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__options, 1),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [350] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_optionblock_repeat1, 2), SHIFT_REPEAT(94),
  [353] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_optionblock_repeat1, 2),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [359] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__options, 3),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [363] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_optionblock_repeat1, 3),
  [365] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_ConTeXt(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
