#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 124
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 62
#define ALIAS_COUNT 0
#define TOKEN_COUNT 34
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_BSLASHstarttext = 1,
  anon_sym_BSLASHstartcomponent = 2,
  anon_sym_BSLASHstoptext = 3,
  anon_sym_BSLASHstopcomponent = 4,
  aux_sym_comment_token1 = 5,
  anon_sym_POUND = 6,
  anon_sym_DOLLAR = 7,
  anon_sym_PERCENT = 8,
  anon_sym_AMP = 9,
  anon_sym_CARET = 10,
  anon_sym__ = 11,
  anon_sym_LBRACE = 12,
  anon_sym_RBRACE = 13,
  anon_sym_PIPE = 14,
  anon_sym_TILDE = 15,
  anon_sym_BSLASH = 16,
  anon_sym_BSLASHegroup = 17,
  anon_sym_BSLASHbgroup = 18,
  aux_sym_command_group_token1 = 19,
  aux_sym_command_group_token2 = 20,
  sym_math_text = 21,
  sym_command_name = 22,
  anon_sym_LBRACK = 23,
  anon_sym_COMMA = 24,
  anon_sym_RBRACK = 25,
  aux_sym_keyword_token1 = 26,
  anon_sym_EQ = 27,
  sym_value_text = 28,
  sym_text = 29,
  anon_sym_LF = 30,
  anon_sym_CR = 31,
  anon_sym_CR_LF = 32,
  sym_command_stop = 33,
  sym_document = 34,
  sym__content = 35,
  sym_main_start = 36,
  sym_main_stop = 37,
  sym_comment = 38,
  sym_escapechar = 39,
  sym_escaped = 40,
  sym_brace_group = 41,
  sym_command_group = 42,
  sym_math_group = 43,
  sym__math_content = 44,
  sym_inline_math = 45,
  sym_optionblock = 46,
  sym_keyword = 47,
  sym_settingsblock = 48,
  sym_setting = 49,
  sym_key = 50,
  sym_value = 51,
  sym__value_content = 52,
  sym_value_brace_group = 53,
  sym_command = 54,
  sym__end_of_line = 55,
  aux_sym_document_repeat1 = 56,
  aux_sym_math_group_repeat1 = 57,
  aux_sym_optionblock_repeat1 = 58,
  aux_sym_settingsblock_repeat1 = 59,
  aux_sym_value_repeat1 = 60,
  aux_sym_command_repeat1 = 61,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_BSLASHstarttext] = "\\starttext",
  [anon_sym_BSLASHstartcomponent] = "\\startcomponent",
  [anon_sym_BSLASHstoptext] = "\\stoptext",
  [anon_sym_BSLASHstopcomponent] = "\\stopcomponent",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_POUND] = "#",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_PERCENT] = "%",
  [anon_sym_AMP] = "&",
  [anon_sym_CARET] = "^",
  [anon_sym__] = "_",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_PIPE] = "|",
  [anon_sym_TILDE] = "~",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_BSLASHegroup] = "\\egroup",
  [anon_sym_BSLASHbgroup] = "\\bgroup",
  [aux_sym_command_group_token1] = "command_group_token1",
  [aux_sym_command_group_token2] = "command_group_token2",
  [sym_math_text] = "math_text",
  [sym_command_name] = "command_name",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [aux_sym_keyword_token1] = "keyword_token1",
  [anon_sym_EQ] = "=",
  [sym_value_text] = "value_text",
  [sym_text] = "text",
  [anon_sym_LF] = "\n",
  [anon_sym_CR] = "\r",
  [anon_sym_CR_LF] = "\r\n",
  [sym_command_stop] = "command_stop",
  [sym_document] = "document",
  [sym__content] = "_content",
  [sym_main_start] = "main_start",
  [sym_main_stop] = "main_stop",
  [sym_comment] = "comment",
  [sym_escapechar] = "escapechar",
  [sym_escaped] = "escaped",
  [sym_brace_group] = "brace_group",
  [sym_command_group] = "command_group",
  [sym_math_group] = "math_group",
  [sym__math_content] = "_math_content",
  [sym_inline_math] = "inline_math",
  [sym_optionblock] = "optionblock",
  [sym_keyword] = "keyword",
  [sym_settingsblock] = "settingsblock",
  [sym_setting] = "setting",
  [sym_key] = "key",
  [sym_value] = "value",
  [sym__value_content] = "_value_content",
  [sym_value_brace_group] = "value_brace_group",
  [sym_command] = "command",
  [sym__end_of_line] = "_end_of_line",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_math_group_repeat1] = "math_group_repeat1",
  [aux_sym_optionblock_repeat1] = "optionblock_repeat1",
  [aux_sym_settingsblock_repeat1] = "settingsblock_repeat1",
  [aux_sym_value_repeat1] = "value_repeat1",
  [aux_sym_command_repeat1] = "command_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_BSLASHstarttext] = anon_sym_BSLASHstarttext,
  [anon_sym_BSLASHstartcomponent] = anon_sym_BSLASHstartcomponent,
  [anon_sym_BSLASHstoptext] = anon_sym_BSLASHstoptext,
  [anon_sym_BSLASHstopcomponent] = anon_sym_BSLASHstopcomponent,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym__] = anon_sym__,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_BSLASHegroup] = anon_sym_BSLASHegroup,
  [anon_sym_BSLASHbgroup] = anon_sym_BSLASHbgroup,
  [aux_sym_command_group_token1] = aux_sym_command_group_token1,
  [aux_sym_command_group_token2] = aux_sym_command_group_token2,
  [sym_math_text] = sym_math_text,
  [sym_command_name] = sym_command_name,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [aux_sym_keyword_token1] = aux_sym_keyword_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_value_text] = sym_value_text,
  [sym_text] = sym_text,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_CR] = anon_sym_CR,
  [anon_sym_CR_LF] = anon_sym_CR_LF,
  [sym_command_stop] = sym_command_stop,
  [sym_document] = sym_document,
  [sym__content] = sym__content,
  [sym_main_start] = sym_main_start,
  [sym_main_stop] = sym_main_stop,
  [sym_comment] = sym_comment,
  [sym_escapechar] = sym_escapechar,
  [sym_escaped] = sym_escaped,
  [sym_brace_group] = sym_brace_group,
  [sym_command_group] = sym_command_group,
  [sym_math_group] = sym_math_group,
  [sym__math_content] = sym__math_content,
  [sym_inline_math] = sym_inline_math,
  [sym_optionblock] = sym_optionblock,
  [sym_keyword] = sym_keyword,
  [sym_settingsblock] = sym_settingsblock,
  [sym_setting] = sym_setting,
  [sym_key] = sym_key,
  [sym_value] = sym_value,
  [sym__value_content] = sym__value_content,
  [sym_value_brace_group] = sym_value_brace_group,
  [sym_command] = sym_command,
  [sym__end_of_line] = sym__end_of_line,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_math_group_repeat1] = aux_sym_math_group_repeat1,
  [aux_sym_optionblock_repeat1] = aux_sym_optionblock_repeat1,
  [aux_sym_settingsblock_repeat1] = aux_sym_settingsblock_repeat1,
  [aux_sym_value_repeat1] = aux_sym_value_repeat1,
  [aux_sym_command_repeat1] = aux_sym_command_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BSLASHstarttext] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHstartcomponent] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHstoptext] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHstopcomponent] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHegroup] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASHbgroup] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_command_group_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_command_group_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_math_text] = {
    .visible = true,
    .named = true,
  },
  [sym_command_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_keyword_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_value_text] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_command_stop] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__content] = {
    .visible = false,
    .named = true,
  },
  [sym_main_start] = {
    .visible = true,
    .named = true,
  },
  [sym_main_stop] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_escapechar] = {
    .visible = true,
    .named = true,
  },
  [sym_escaped] = {
    .visible = true,
    .named = true,
  },
  [sym_brace_group] = {
    .visible = true,
    .named = true,
  },
  [sym_command_group] = {
    .visible = true,
    .named = true,
  },
  [sym_math_group] = {
    .visible = true,
    .named = true,
  },
  [sym__math_content] = {
    .visible = false,
    .named = true,
  },
  [sym_inline_math] = {
    .visible = true,
    .named = true,
  },
  [sym_optionblock] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_settingsblock] = {
    .visible = true,
    .named = true,
  },
  [sym_setting] = {
    .visible = true,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym__value_content] = {
    .visible = false,
    .named = true,
  },
  [sym_value_brace_group] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym__end_of_line] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_math_group_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_optionblock_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_settingsblock_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_command_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(51);
      if (lookahead == '#') ADVANCE(59);
      if (lookahead == '$') ADVANCE(60);
      if (lookahead == '%') ADVANCE(61);
      if (lookahead == '&') ADVANCE(62);
      if (lookahead == ',') ADVANCE(83);
      if (lookahead == '=') ADVANCE(86);
      if (lookahead == '[') ADVANCE(82);
      if (lookahead == '\\') ADVANCE(70);
      if (lookahead == ']') ADVANCE(84);
      if (lookahead == '^') ADVANCE(63);
      if (lookahead == '_') ADVANCE(64);
      if (lookahead == '{') ADVANCE(65);
      if (lookahead == '|') ADVANCE(67);
      if (lookahead == '}') ADVANCE(66);
      if (lookahead == '~') ADVANCE(68);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(90);
      if (lookahead == '\r') ADVANCE(92);
      if (lookahead == '$') ADVANCE(60);
      if (lookahead == '%') ADVANCE(58);
      if (lookahead == '\\') ADVANCE(72);
      if (lookahead == '{') ADVANCE(65);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '&' &&
          (lookahead < '[' || '_' < lookahead) &&
          (lookahead < '|' || '~' < lookahead)) ADVANCE(89);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(90);
      if (lookahead == '\r') ADVANCE(92);
      if (lookahead == '$') ADVANCE(60);
      if (lookahead == '%') ADVANCE(58);
      if (lookahead == '\\') ADVANCE(71);
      if (lookahead == '{') ADVANCE(65);
      if (lookahead == '}') ADVANCE(66);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '&' &&
          (lookahead < '[' || '_' < lookahead) &&
          (lookahead < '|' || '~' < lookahead)) ADVANCE(89);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(91);
      if (lookahead == '\r') ADVANCE(93);
      if (lookahead == '%') ADVANCE(56);
      if (lookahead == ',') ADVANCE(83);
      if (lookahead == '\\') ADVANCE(69);
      if (lookahead == ']') ADVANCE(84);
      if (lookahead == '{') ADVANCE(65);
      if (lookahead == '}') ADVANCE(66);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3)
      if (lookahead != 0 &&
          lookahead != '[') ADVANCE(87);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(59);
      if (lookahead == '$') ADVANCE(60);
      if (lookahead == '%') ADVANCE(61);
      if (lookahead == '&') ADVANCE(62);
      if (lookahead == '\\') ADVANCE(69);
      if (lookahead == '^') ADVANCE(63);
      if (lookahead == '_') ADVANCE(64);
      if (lookahead == '{') ADVANCE(65);
      if (lookahead == '|') ADVANCE(67);
      if (lookahead == '}') ADVANCE(66);
      if (lookahead == '~') ADVANCE(68);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 5:
      if (lookahead == '$') ADVANCE(60);
      if (lookahead == '%') ADVANCE(57);
      if (lookahead == '\\') ADVANCE(74);
      if (lookahead == '{') ADVANCE(65);
      if (lookahead == '}') ADVANCE(66);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(79);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 6:
      if (lookahead == ',') ADVANCE(83);
      if (lookahead == ']') ADVANCE(84);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      if (lookahead != 0 &&
          lookahead != '=' &&
          lookahead != '[') ADVANCE(85);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(37);
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(37);
      if (lookahead == 'o') ADVANCE(33);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(25);
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(25);
      if (lookahead == 't') ADVANCE(12);
      if (lookahead != 0 &&
          (lookahead < 'A' || 'Z' < lookahead) &&
          (lookahead < 'a' || 'z' < lookahead)) ADVANCE(78);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(29);
      if (lookahead == 't') ADVANCE(14);
      if (lookahead != 0 &&
          (lookahead < 'A' || 'Z' < lookahead) &&
          (lookahead < 'a' || 'z' < lookahead)) ADVANCE(77);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 'g') ADVANCE(36);
      END_STATE();
    case 17:
      if (lookahead == 'g') ADVANCE(38);
      END_STATE();
    case 18:
      if (lookahead == 'm') ADVANCE(34);
      END_STATE();
    case 19:
      if (lookahead == 'm') ADVANCE(35);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(42);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(43);
      END_STATE();
    case 23:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 24:
      if (lookahead == 'o') ADVANCE(46);
      END_STATE();
    case 25:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 26:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(47);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 29:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 30:
      if (lookahead == 'p') ADVANCE(10);
      END_STATE();
    case 31:
      if (lookahead == 'p') ADVANCE(76);
      END_STATE();
    case 32:
      if (lookahead == 'p') ADVANCE(75);
      END_STATE();
    case 33:
      if (lookahead == 'p') ADVANCE(9);
      END_STATE();
    case 34:
      if (lookahead == 'p') ADVANCE(26);
      END_STATE();
    case 35:
      if (lookahead == 'p') ADVANCE(28);
      END_STATE();
    case 36:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 37:
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 39:
      if (lookahead == 't') ADVANCE(7);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(54);
      END_STATE();
    case 41:
      if (lookahead == 't') ADVANCE(52);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(55);
      END_STATE();
    case 43:
      if (lookahead == 't') ADVANCE(53);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(11);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 46:
      if (lookahead == 'u') ADVANCE(31);
      END_STATE();
    case 47:
      if (lookahead == 'u') ADVANCE(32);
      END_STATE();
    case 48:
      if (lookahead == 'x') ADVANCE(40);
      END_STATE();
    case 49:
      if (lookahead == 'x') ADVANCE(41);
      END_STATE();
    case 50:
      if (eof) ADVANCE(51);
      if (lookahead == '\n') ADVANCE(90);
      if (lookahead == '\r') ADVANCE(92);
      if (lookahead == '$') ADVANCE(60);
      if (lookahead == '%') ADVANCE(58);
      if (lookahead == '\\') ADVANCE(73);
      if (lookahead == '{') ADVANCE(65);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '&' &&
          (lookahead < '[' || '_' < lookahead) &&
          (lookahead < '|' || '~' < lookahead)) ADVANCE(89);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_BSLASHstarttext);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_BSLASHstartcomponent);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_BSLASHstoptext);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_BSLASHstopcomponent);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\n') ADVANCE(87);
      if (lookahead == ',' ||
          ('[' <= lookahead && lookahead <= ']') ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(58);
      if (lookahead != 0) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\n') ADVANCE(80);
      if (lookahead == '$' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(58);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == 'b') ADVANCE(16);
      if (lookahead == 'e') ADVANCE(17);
      if (lookahead == 's') ADVANCE(39);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == 'b') ADVANCE(16);
      if (lookahead == 'e') ADVANCE(17);
      if (lookahead == 's') ADVANCE(45);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == 'b') ADVANCE(16);
      if (lookahead == 's') ADVANCE(39);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead == 'b') ADVANCE(16);
      if (lookahead == 's') ADVANCE(45);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_BSLASHegroup);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_BSLASHbgroup);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_command_group_token1);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_command_group_token2);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_math_text);
      if (lookahead == '%') ADVANCE(57);
      if (lookahead == '\\') ADVANCE(74);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_math_text);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_command_name);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_keyword_token1);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != ',' &&
          lookahead != '=' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_value_text);
      if (lookahead != 0 &&
          lookahead != ',' &&
          (lookahead < '[' || ']' < lookahead) &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(87);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '\n') ADVANCE(90);
      if (lookahead == '\r') ADVANCE(92);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0 &&
          (lookahead < '$' || '&' < lookahead) &&
          (lookahead < '[' || '_' < lookahead) &&
          (lookahead < '{' || '~' < lookahead)) ADVANCE(89);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          (lookahead < '$' || '&' < lookahead) &&
          (lookahead < '[' || '_' < lookahead) &&
          (lookahead < '{' || '~' < lookahead)) ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(90);
      if (lookahead == '\r') ADVANCE(92);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(88);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(91);
      if (lookahead == '\r') ADVANCE(93);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_CR);
      if (lookahead == '\n') ADVANCE(90);
      if (lookahead == '\r') ADVANCE(92);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(88);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_CR);
      if (lookahead == '\n') ADVANCE(91);
      if (lookahead == '\r') ADVANCE(93);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 50},
  [2] = {.lex_state = 2},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 50},
  [14] = {.lex_state = 50},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 50},
  [34] = {.lex_state = 50},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 50},
  [37] = {.lex_state = 50},
  [38] = {.lex_state = 50},
  [39] = {.lex_state = 50},
  [40] = {.lex_state = 50},
  [41] = {.lex_state = 50},
  [42] = {.lex_state = 50},
  [43] = {.lex_state = 50},
  [44] = {.lex_state = 50},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 50},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 4},
  [60] = {.lex_state = 4},
  [61] = {.lex_state = 4},
  [62] = {.lex_state = 4},
  [63] = {.lex_state = 4},
  [64] = {.lex_state = 5},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 5},
  [70] = {.lex_state = 3},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 5},
  [73] = {.lex_state = 3},
  [74] = {.lex_state = 5},
  [75] = {.lex_state = 5},
  [76] = {.lex_state = 5},
  [77] = {.lex_state = 5},
  [78] = {.lex_state = 5},
  [79] = {.lex_state = 5},
  [80] = {.lex_state = 5},
  [81] = {.lex_state = 5},
  [82] = {.lex_state = 5},
  [83] = {.lex_state = 5},
  [84] = {.lex_state = 6},
  [85] = {.lex_state = 5},
  [86] = {.lex_state = 0, .external_lex_state = 1},
  [87] = {.lex_state = 0, .external_lex_state = 1},
  [88] = {.lex_state = 0, .external_lex_state = 1},
  [89] = {.lex_state = 0, .external_lex_state = 1},
  [90] = {.lex_state = 0, .external_lex_state = 1},
  [91] = {.lex_state = 0, .external_lex_state = 1},
  [92] = {.lex_state = 0, .external_lex_state = 1},
  [93] = {.lex_state = 0, .external_lex_state = 1},
  [94] = {.lex_state = 0, .external_lex_state = 1},
  [95] = {.lex_state = 6},
  [96] = {.lex_state = 6},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 6},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 6},
  [106] = {.lex_state = 6},
  [107] = {.lex_state = 0, .external_lex_state = 1},
  [108] = {.lex_state = 0, .external_lex_state = 1},
  [109] = {.lex_state = 0, .external_lex_state = 1},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0, .external_lex_state = 1},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0, .external_lex_state = 1},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0, .external_lex_state = 1},
  [117] = {.lex_state = 6},
  [118] = {.lex_state = 0, .external_lex_state = 1},
  [119] = {.lex_state = 0, .external_lex_state = 1},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
};

enum {
  ts_external_token_command_stop = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_command_stop] = sym_command_stop,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_command_stop] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_BSLASHstarttext] = ACTIONS(1),
    [anon_sym_BSLASHstartcomponent] = ACTIONS(1),
    [anon_sym_BSLASHstoptext] = ACTIONS(1),
    [anon_sym_BSLASHstopcomponent] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_BSLASHegroup] = ACTIONS(1),
    [anon_sym_BSLASHbgroup] = ACTIONS(1),
    [aux_sym_command_group_token1] = ACTIONS(1),
    [aux_sym_command_group_token2] = ACTIONS(1),
    [sym_command_name] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_command_stop] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(120),
    [sym__content] = STATE(13),
    [sym_main_start] = STATE(13),
    [sym_main_stop] = STATE(13),
    [sym_comment] = STATE(13),
    [sym_escaped] = STATE(13),
    [sym_brace_group] = STATE(13),
    [sym_command_group] = STATE(13),
    [sym_inline_math] = STATE(13),
    [sym_command] = STATE(13),
    [sym__end_of_line] = STATE(13),
    [aux_sym_document_repeat1] = STATE(13),
    [anon_sym_BSLASHstarttext] = ACTIONS(3),
    [anon_sym_BSLASHstartcomponent] = ACTIONS(3),
    [anon_sym_BSLASHstoptext] = ACTIONS(5),
    [anon_sym_BSLASHstopcomponent] = ACTIONS(5),
    [aux_sym_comment_token1] = ACTIONS(7),
    [anon_sym_DOLLAR] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_BSLASH] = ACTIONS(13),
    [anon_sym_BSLASHbgroup] = ACTIONS(11),
    [aux_sym_command_group_token1] = ACTIONS(15),
    [sym_text] = ACTIONS(17),
    [anon_sym_LF] = ACTIONS(17),
    [anon_sym_CR] = ACTIONS(17),
    [anon_sym_CR_LF] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(25), 1,
      aux_sym_comment_token1,
    ACTIONS(28), 1,
      anon_sym_DOLLAR,
    ACTIONS(36), 1,
      anon_sym_BSLASH,
    ACTIONS(39), 1,
      aux_sym_command_group_token1,
    ACTIONS(19), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(22), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(31), 2,
      anon_sym_LBRACE,
      anon_sym_BSLASHbgroup,
    ACTIONS(34), 2,
      anon_sym_RBRACE,
      anon_sym_BSLASHegroup,
    ACTIONS(42), 4,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
    STATE(2), 11,
      sym__content,
      sym_main_start,
      sym_main_stop,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_command_group,
      sym_inline_math,
      sym_command,
      sym__end_of_line,
      aux_sym_document_repeat1,
  [48] = 10,
    ACTIONS(49), 1,
      aux_sym_comment_token1,
    ACTIONS(51), 1,
      anon_sym_DOLLAR,
    ACTIONS(57), 1,
      anon_sym_BSLASH,
    ACTIONS(59), 1,
      aux_sym_command_group_token1,
    ACTIONS(45), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(47), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(53), 2,
      anon_sym_LBRACE,
      anon_sym_BSLASHbgroup,
    ACTIONS(55), 2,
      anon_sym_RBRACE,
      anon_sym_BSLASHegroup,
    ACTIONS(61), 4,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
    STATE(7), 11,
      sym__content,
      sym_main_start,
      sym_main_stop,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_command_group,
      sym_inline_math,
      sym_command,
      sym__end_of_line,
      aux_sym_document_repeat1,
  [96] = 10,
    ACTIONS(49), 1,
      aux_sym_comment_token1,
    ACTIONS(51), 1,
      anon_sym_DOLLAR,
    ACTIONS(57), 1,
      anon_sym_BSLASH,
    ACTIONS(59), 1,
      aux_sym_command_group_token1,
    ACTIONS(45), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(47), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(53), 2,
      anon_sym_LBRACE,
      anon_sym_BSLASHbgroup,
    ACTIONS(63), 2,
      anon_sym_RBRACE,
      anon_sym_BSLASHegroup,
    ACTIONS(65), 4,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
    STATE(8), 11,
      sym__content,
      sym_main_start,
      sym_main_stop,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_command_group,
      sym_inline_math,
      sym_command,
      sym__end_of_line,
      aux_sym_document_repeat1,
  [144] = 10,
    ACTIONS(49), 1,
      aux_sym_comment_token1,
    ACTIONS(51), 1,
      anon_sym_DOLLAR,
    ACTIONS(57), 1,
      anon_sym_BSLASH,
    ACTIONS(59), 1,
      aux_sym_command_group_token1,
    ACTIONS(45), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(47), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(53), 2,
      anon_sym_LBRACE,
      anon_sym_BSLASHbgroup,
    ACTIONS(67), 2,
      anon_sym_RBRACE,
      anon_sym_BSLASHegroup,
    ACTIONS(69), 4,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
    STATE(2), 11,
      sym__content,
      sym_main_start,
      sym_main_stop,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_command_group,
      sym_inline_math,
      sym_command,
      sym__end_of_line,
      aux_sym_document_repeat1,
  [192] = 10,
    ACTIONS(49), 1,
      aux_sym_comment_token1,
    ACTIONS(51), 1,
      anon_sym_DOLLAR,
    ACTIONS(57), 1,
      anon_sym_BSLASH,
    ACTIONS(59), 1,
      aux_sym_command_group_token1,
    ACTIONS(45), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(47), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(53), 2,
      anon_sym_LBRACE,
      anon_sym_BSLASHbgroup,
    ACTIONS(71), 2,
      anon_sym_RBRACE,
      anon_sym_BSLASHegroup,
    ACTIONS(73), 4,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
    STATE(5), 11,
      sym__content,
      sym_main_start,
      sym_main_stop,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_command_group,
      sym_inline_math,
      sym_command,
      sym__end_of_line,
      aux_sym_document_repeat1,
  [240] = 10,
    ACTIONS(49), 1,
      aux_sym_comment_token1,
    ACTIONS(51), 1,
      anon_sym_DOLLAR,
    ACTIONS(57), 1,
      anon_sym_BSLASH,
    ACTIONS(59), 1,
      aux_sym_command_group_token1,
    ACTIONS(45), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(47), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(53), 2,
      anon_sym_LBRACE,
      anon_sym_BSLASHbgroup,
    ACTIONS(75), 2,
      anon_sym_RBRACE,
      anon_sym_BSLASHegroup,
    ACTIONS(69), 4,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
    STATE(2), 11,
      sym__content,
      sym_main_start,
      sym_main_stop,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_command_group,
      sym_inline_math,
      sym_command,
      sym__end_of_line,
      aux_sym_document_repeat1,
  [288] = 10,
    ACTIONS(49), 1,
      aux_sym_comment_token1,
    ACTIONS(51), 1,
      anon_sym_DOLLAR,
    ACTIONS(57), 1,
      anon_sym_BSLASH,
    ACTIONS(59), 1,
      aux_sym_command_group_token1,
    ACTIONS(45), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(47), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(53), 2,
      anon_sym_LBRACE,
      anon_sym_BSLASHbgroup,
    ACTIONS(77), 2,
      anon_sym_RBRACE,
      anon_sym_BSLASHegroup,
    ACTIONS(69), 4,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
    STATE(2), 11,
      sym__content,
      sym_main_start,
      sym_main_stop,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_command_group,
      sym_inline_math,
      sym_command,
      sym__end_of_line,
      aux_sym_document_repeat1,
  [336] = 10,
    ACTIONS(83), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_DOLLAR,
    ACTIONS(89), 1,
      anon_sym_BSLASH,
    ACTIONS(91), 1,
      aux_sym_command_group_token1,
    ACTIONS(93), 1,
      aux_sym_command_group_token2,
    ACTIONS(79), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(81), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(87), 2,
      anon_sym_LBRACE,
      anon_sym_BSLASHbgroup,
    ACTIONS(95), 4,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
    STATE(10), 11,
      sym__content,
      sym_main_start,
      sym_main_stop,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_command_group,
      sym_inline_math,
      sym_command,
      sym__end_of_line,
      aux_sym_document_repeat1,
  [383] = 10,
    ACTIONS(34), 1,
      aux_sym_command_group_token2,
    ACTIONS(103), 1,
      aux_sym_comment_token1,
    ACTIONS(106), 1,
      anon_sym_DOLLAR,
    ACTIONS(112), 1,
      anon_sym_BSLASH,
    ACTIONS(115), 1,
      aux_sym_command_group_token1,
    ACTIONS(97), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(100), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(109), 2,
      anon_sym_LBRACE,
      anon_sym_BSLASHbgroup,
    ACTIONS(118), 4,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
    STATE(10), 11,
      sym__content,
      sym_main_start,
      sym_main_stop,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_command_group,
      sym_inline_math,
      sym_command,
      sym__end_of_line,
      aux_sym_document_repeat1,
  [430] = 10,
    ACTIONS(83), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_DOLLAR,
    ACTIONS(89), 1,
      anon_sym_BSLASH,
    ACTIONS(91), 1,
      aux_sym_command_group_token1,
    ACTIONS(121), 1,
      aux_sym_command_group_token2,
    ACTIONS(79), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(81), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(87), 2,
      anon_sym_LBRACE,
      anon_sym_BSLASHbgroup,
    ACTIONS(123), 4,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
    STATE(9), 11,
      sym__content,
      sym_main_start,
      sym_main_stop,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_command_group,
      sym_inline_math,
      sym_command,
      sym__end_of_line,
      aux_sym_document_repeat1,
  [477] = 10,
    ACTIONS(83), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_DOLLAR,
    ACTIONS(89), 1,
      anon_sym_BSLASH,
    ACTIONS(91), 1,
      aux_sym_command_group_token1,
    ACTIONS(125), 1,
      aux_sym_command_group_token2,
    ACTIONS(79), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(81), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(87), 2,
      anon_sym_LBRACE,
      anon_sym_BSLASHbgroup,
    ACTIONS(127), 4,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
    STATE(15), 11,
      sym__content,
      sym_main_start,
      sym_main_stop,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_command_group,
      sym_inline_math,
      sym_command,
      sym__end_of_line,
      aux_sym_document_repeat1,
  [524] = 10,
    ACTIONS(7), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      anon_sym_DOLLAR,
    ACTIONS(13), 1,
      anon_sym_BSLASH,
    ACTIONS(15), 1,
      aux_sym_command_group_token1,
    ACTIONS(129), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(5), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(11), 2,
      anon_sym_LBRACE,
      anon_sym_BSLASHbgroup,
    ACTIONS(131), 4,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
    STATE(14), 11,
      sym__content,
      sym_main_start,
      sym_main_stop,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_command_group,
      sym_inline_math,
      sym_command,
      sym__end_of_line,
      aux_sym_document_repeat1,
  [571] = 10,
    ACTIONS(133), 1,
      ts_builtin_sym_end,
    ACTIONS(141), 1,
      aux_sym_comment_token1,
    ACTIONS(144), 1,
      anon_sym_DOLLAR,
    ACTIONS(150), 1,
      anon_sym_BSLASH,
    ACTIONS(153), 1,
      aux_sym_command_group_token1,
    ACTIONS(135), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(138), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(147), 2,
      anon_sym_LBRACE,
      anon_sym_BSLASHbgroup,
    ACTIONS(156), 4,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
    STATE(14), 11,
      sym__content,
      sym_main_start,
      sym_main_stop,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_command_group,
      sym_inline_math,
      sym_command,
      sym__end_of_line,
      aux_sym_document_repeat1,
  [618] = 10,
    ACTIONS(83), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_DOLLAR,
    ACTIONS(89), 1,
      anon_sym_BSLASH,
    ACTIONS(91), 1,
      aux_sym_command_group_token1,
    ACTIONS(159), 1,
      aux_sym_command_group_token2,
    ACTIONS(79), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(81), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(87), 2,
      anon_sym_LBRACE,
      anon_sym_BSLASHbgroup,
    ACTIONS(95), 4,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
    STATE(10), 11,
      sym__content,
      sym_main_start,
      sym_main_stop,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_command_group,
      sym_inline_math,
      sym_command,
      sym__end_of_line,
      aux_sym_document_repeat1,
  [665] = 10,
    ACTIONS(83), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_DOLLAR,
    ACTIONS(89), 1,
      anon_sym_BSLASH,
    ACTIONS(91), 1,
      aux_sym_command_group_token1,
    ACTIONS(161), 1,
      aux_sym_command_group_token2,
    ACTIONS(79), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(81), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(87), 2,
      anon_sym_LBRACE,
      anon_sym_BSLASHbgroup,
    ACTIONS(163), 4,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
    STATE(17), 11,
      sym__content,
      sym_main_start,
      sym_main_stop,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_command_group,
      sym_inline_math,
      sym_command,
      sym__end_of_line,
      aux_sym_document_repeat1,
  [712] = 10,
    ACTIONS(83), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_DOLLAR,
    ACTIONS(89), 1,
      anon_sym_BSLASH,
    ACTIONS(91), 1,
      aux_sym_command_group_token1,
    ACTIONS(165), 1,
      aux_sym_command_group_token2,
    ACTIONS(79), 2,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
    ACTIONS(81), 2,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
    ACTIONS(87), 2,
      anon_sym_LBRACE,
      anon_sym_BSLASHbgroup,
    ACTIONS(95), 4,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
    STATE(10), 11,
      sym__content,
      sym_main_start,
      sym_main_stop,
      sym_comment,
      sym_escaped,
      sym_brace_group,
      sym_command_group,
      sym_inline_math,
      sym_command,
      sym__end_of_line,
      aux_sym_document_repeat1,
  [759] = 6,
    ACTIONS(167), 1,
      aux_sym_comment_token1,
    ACTIONS(170), 1,
      anon_sym_LBRACE,
    ACTIONS(175), 1,
      anon_sym_BSLASH,
    ACTIONS(173), 3,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    ACTIONS(178), 4,
      sym_value_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
    STATE(18), 7,
      sym_comment,
      sym_escaped,
      sym__value_content,
      sym_value_brace_group,
      sym_command,
      sym__end_of_line,
      aux_sym_value_repeat1,
  [789] = 7,
    ACTIONS(181), 1,
      aux_sym_comment_token1,
    ACTIONS(183), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_BSLASH,
    STATE(115), 1,
      sym_value,
    ACTIONS(187), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    ACTIONS(189), 4,
      sym_value_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
    STATE(21), 7,
      sym_comment,
      sym_escaped,
      sym__value_content,
      sym_value_brace_group,
      sym_command,
      sym__end_of_line,
      aux_sym_value_repeat1,
  [821] = 1,
    ACTIONS(191), 16,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHegroup,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [840] = 6,
    ACTIONS(181), 1,
      aux_sym_comment_token1,
    ACTIONS(183), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_BSLASH,
    ACTIONS(193), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
    ACTIONS(195), 4,
      sym_value_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
    STATE(18), 7,
      sym_comment,
      sym_escaped,
      sym__value_content,
      sym_value_brace_group,
      sym_command,
      sym__end_of_line,
      aux_sym_value_repeat1,
  [869] = 1,
    ACTIONS(197), 16,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHegroup,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [888] = 1,
    ACTIONS(199), 16,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHegroup,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [907] = 1,
    ACTIONS(201), 16,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHegroup,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [926] = 1,
    ACTIONS(203), 16,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHegroup,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [945] = 1,
    ACTIONS(205), 16,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHegroup,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [964] = 1,
    ACTIONS(207), 16,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHegroup,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [983] = 1,
    ACTIONS(209), 16,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHegroup,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1002] = 1,
    ACTIONS(211), 16,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHegroup,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1021] = 1,
    ACTIONS(213), 16,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHegroup,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1040] = 1,
    ACTIONS(215), 16,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHegroup,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1059] = 1,
    ACTIONS(217), 16,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHegroup,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1078] = 2,
    ACTIONS(219), 1,
      ts_builtin_sym_end,
    ACTIONS(199), 14,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1098] = 2,
    ACTIONS(221), 1,
      ts_builtin_sym_end,
    ACTIONS(215), 14,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1118] = 1,
    ACTIONS(213), 15,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      aux_sym_command_group_token2,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1136] = 2,
    ACTIONS(223), 1,
      ts_builtin_sym_end,
    ACTIONS(209), 14,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1156] = 2,
    ACTIONS(225), 1,
      ts_builtin_sym_end,
    ACTIONS(217), 14,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1176] = 2,
    ACTIONS(227), 1,
      ts_builtin_sym_end,
    ACTIONS(197), 14,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1196] = 2,
    ACTIONS(229), 1,
      ts_builtin_sym_end,
    ACTIONS(191), 14,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1216] = 2,
    ACTIONS(231), 1,
      ts_builtin_sym_end,
    ACTIONS(213), 14,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1236] = 2,
    ACTIONS(233), 1,
      ts_builtin_sym_end,
    ACTIONS(211), 14,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1256] = 2,
    ACTIONS(235), 1,
      ts_builtin_sym_end,
    ACTIONS(207), 14,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1276] = 2,
    ACTIONS(237), 1,
      ts_builtin_sym_end,
    ACTIONS(205), 14,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1296] = 2,
    ACTIONS(239), 1,
      ts_builtin_sym_end,
    ACTIONS(201), 14,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1316] = 6,
    ACTIONS(181), 1,
      aux_sym_comment_token1,
    ACTIONS(183), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_BSLASH,
    ACTIONS(241), 1,
      anon_sym_RBRACE,
    ACTIONS(195), 4,
      sym_value_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
    STATE(18), 7,
      sym_comment,
      sym_escaped,
      sym__value_content,
      sym_value_brace_group,
      sym_command,
      sym__end_of_line,
      aux_sym_value_repeat1,
  [1344] = 1,
    ACTIONS(209), 15,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      aux_sym_command_group_token2,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1362] = 2,
    ACTIONS(243), 1,
      ts_builtin_sym_end,
    ACTIONS(203), 14,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1382] = 1,
    ACTIONS(211), 15,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      aux_sym_command_group_token2,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1400] = 1,
    ACTIONS(191), 15,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      aux_sym_command_group_token2,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1418] = 1,
    ACTIONS(217), 15,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      aux_sym_command_group_token2,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1436] = 1,
    ACTIONS(215), 15,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      aux_sym_command_group_token2,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1454] = 1,
    ACTIONS(197), 15,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      aux_sym_command_group_token2,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1472] = 1,
    ACTIONS(199), 15,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      aux_sym_command_group_token2,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1490] = 1,
    ACTIONS(201), 15,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      aux_sym_command_group_token2,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1508] = 1,
    ACTIONS(203), 15,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      aux_sym_command_group_token2,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1526] = 1,
    ACTIONS(205), 15,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      aux_sym_command_group_token2,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1544] = 1,
    ACTIONS(207), 15,
      anon_sym_BSLASHstarttext,
      anon_sym_BSLASHstartcomponent,
      anon_sym_BSLASHstoptext,
      anon_sym_BSLASHstopcomponent,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_BSLASH,
      anon_sym_BSLASHbgroup,
      aux_sym_command_group_token1,
      aux_sym_command_group_token2,
      sym_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1562] = 6,
    ACTIONS(181), 1,
      aux_sym_comment_token1,
    ACTIONS(183), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 1,
      anon_sym_BSLASH,
    ACTIONS(245), 1,
      anon_sym_RBRACE,
    ACTIONS(247), 4,
      sym_value_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
    STATE(45), 7,
      sym_comment,
      sym_escaped,
      sym__value_content,
      sym_value_brace_group,
      sym_command,
      sym__end_of_line,
      aux_sym_value_repeat1,
  [1590] = 3,
    ACTIONS(251), 1,
      sym_command_name,
    STATE(65), 1,
      sym_escapechar,
    ACTIONS(249), 11,
      anon_sym_POUND,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_AMP,
      anon_sym_CARET,
      anon_sym__,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_BSLASH,
  [1610] = 3,
    ACTIONS(255), 1,
      sym_command_name,
    STATE(49), 1,
      sym_escapechar,
    ACTIONS(253), 11,
      anon_sym_POUND,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_AMP,
      anon_sym_CARET,
      anon_sym__,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_BSLASH,
  [1630] = 3,
    ACTIONS(259), 1,
      sym_command_name,
    STATE(39), 1,
      sym_escapechar,
    ACTIONS(257), 11,
      anon_sym_POUND,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_AMP,
      anon_sym_CARET,
      anon_sym__,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_BSLASH,
  [1650] = 3,
    ACTIONS(263), 1,
      sym_command_name,
    STATE(20), 1,
      sym_escapechar,
    ACTIONS(261), 11,
      anon_sym_POUND,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_AMP,
      anon_sym_CARET,
      anon_sym__,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_BSLASH,
  [1670] = 2,
    STATE(82), 1,
      sym_escapechar,
    ACTIONS(265), 11,
      anon_sym_POUND,
      anon_sym_DOLLAR,
      anon_sym_PERCENT,
      anon_sym_AMP,
      anon_sym_CARET,
      anon_sym__,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE,
      anon_sym_TILDE,
      anon_sym_BSLASH,
  [1687] = 6,
    ACTIONS(267), 1,
      aux_sym_comment_token1,
    ACTIONS(272), 1,
      anon_sym_LBRACE,
    ACTIONS(275), 1,
      anon_sym_BSLASH,
    ACTIONS(278), 1,
      sym_math_text,
    ACTIONS(270), 2,
      anon_sym_DOLLAR,
      anon_sym_RBRACE,
    STATE(64), 5,
      sym_comment,
      sym_escaped,
      sym_math_group,
      sym__math_content,
      aux_sym_math_group_repeat1,
  [1711] = 1,
    ACTIONS(191), 10,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_value_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1724] = 1,
    ACTIONS(215), 10,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_value_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1737] = 1,
    ACTIONS(217), 10,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_value_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1750] = 1,
    ACTIONS(281), 10,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_value_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1763] = 6,
    ACTIONS(283), 1,
      aux_sym_comment_token1,
    ACTIONS(285), 1,
      anon_sym_LBRACE,
    ACTIONS(287), 1,
      anon_sym_RBRACE,
    ACTIONS(289), 1,
      anon_sym_BSLASH,
    ACTIONS(291), 1,
      sym_math_text,
    STATE(64), 5,
      sym_comment,
      sym_escaped,
      sym_math_group,
      sym__math_content,
      aux_sym_math_group_repeat1,
  [1786] = 1,
    ACTIONS(201), 10,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_value_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1799] = 1,
    ACTIONS(293), 10,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_value_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1812] = 6,
    ACTIONS(283), 1,
      aux_sym_comment_token1,
    ACTIONS(285), 1,
      anon_sym_LBRACE,
    ACTIONS(289), 1,
      anon_sym_BSLASH,
    ACTIONS(291), 1,
      sym_math_text,
    ACTIONS(295), 1,
      anon_sym_DOLLAR,
    STATE(64), 5,
      sym_comment,
      sym_escaped,
      sym_math_group,
      sym__math_content,
      aux_sym_math_group_repeat1,
  [1835] = 1,
    ACTIONS(197), 10,
      aux_sym_comment_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      sym_value_text,
      anon_sym_LF,
      anon_sym_CR,
      anon_sym_CR_LF,
  [1848] = 6,
    ACTIONS(283), 1,
      aux_sym_comment_token1,
    ACTIONS(285), 1,
      anon_sym_LBRACE,
    ACTIONS(289), 1,
      anon_sym_BSLASH,
    ACTIONS(291), 1,
      sym_math_text,
    ACTIONS(297), 1,
      anon_sym_DOLLAR,
    STATE(64), 5,
      sym_comment,
      sym_escaped,
      sym_math_group,
      sym__math_content,
      aux_sym_math_group_repeat1,
  [1871] = 6,
    ACTIONS(283), 1,
      aux_sym_comment_token1,
    ACTIONS(285), 1,
      anon_sym_LBRACE,
    ACTIONS(289), 1,
      anon_sym_BSLASH,
    ACTIONS(291), 1,
      sym_math_text,
    ACTIONS(299), 1,
      anon_sym_DOLLAR,
    STATE(64), 5,
      sym_comment,
      sym_escaped,
      sym_math_group,
      sym__math_content,
      aux_sym_math_group_repeat1,
  [1894] = 6,
    ACTIONS(283), 1,
      aux_sym_comment_token1,
    ACTIONS(285), 1,
      anon_sym_LBRACE,
    ACTIONS(289), 1,
      anon_sym_BSLASH,
    ACTIONS(301), 1,
      anon_sym_RBRACE,
    ACTIONS(303), 1,
      sym_math_text,
    STATE(69), 5,
      sym_comment,
      sym_escaped,
      sym_math_group,
      sym__math_content,
      aux_sym_math_group_repeat1,
  [1917] = 5,
    ACTIONS(283), 1,
      aux_sym_comment_token1,
    ACTIONS(285), 1,
      anon_sym_LBRACE,
    ACTIONS(289), 1,
      anon_sym_BSLASH,
    ACTIONS(305), 1,
      sym_math_text,
    STATE(75), 5,
      sym_comment,
      sym_escaped,
      sym_math_group,
      sym__math_content,
      aux_sym_math_group_repeat1,
  [1937] = 5,
    ACTIONS(283), 1,
      aux_sym_comment_token1,
    ACTIONS(285), 1,
      anon_sym_LBRACE,
    ACTIONS(289), 1,
      anon_sym_BSLASH,
    ACTIONS(307), 1,
      sym_math_text,
    STATE(74), 5,
      sym_comment,
      sym_escaped,
      sym_math_group,
      sym__math_content,
      aux_sym_math_group_repeat1,
  [1957] = 5,
    ACTIONS(283), 1,
      aux_sym_comment_token1,
    ACTIONS(285), 1,
      anon_sym_LBRACE,
    ACTIONS(289), 1,
      anon_sym_BSLASH,
    ACTIONS(309), 1,
      sym_math_text,
    STATE(72), 5,
      sym_comment,
      sym_escaped,
      sym_math_group,
      sym__math_content,
      aux_sym_math_group_repeat1,
  [1977] = 1,
    ACTIONS(311), 6,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      sym_math_text,
  [1986] = 1,
    ACTIONS(217), 6,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      sym_math_text,
  [1995] = 1,
    ACTIONS(191), 6,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      sym_math_text,
  [2004] = 1,
    ACTIONS(313), 6,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      sym_math_text,
  [2013] = 6,
    ACTIONS(315), 1,
      anon_sym_COMMA,
    ACTIONS(317), 1,
      anon_sym_RBRACK,
    ACTIONS(319), 1,
      aux_sym_keyword_token1,
    STATE(97), 1,
      sym_setting,
    STATE(104), 1,
      sym_keyword,
    STATE(121), 1,
      sym_key,
  [2032] = 1,
    ACTIONS(215), 6,
      aux_sym_comment_token1,
      anon_sym_DOLLAR,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_BSLASH,
      sym_math_text,
  [2041] = 3,
    ACTIONS(321), 1,
      anon_sym_LBRACK,
    ACTIONS(323), 1,
      sym_command_stop,
    STATE(90), 3,
      sym_optionblock,
      sym_settingsblock,
      aux_sym_command_repeat1,
  [2053] = 3,
    ACTIONS(321), 1,
      anon_sym_LBRACK,
    ACTIONS(325), 1,
      sym_command_stop,
    STATE(94), 3,
      sym_optionblock,
      sym_settingsblock,
      aux_sym_command_repeat1,
  [2065] = 3,
    ACTIONS(321), 1,
      anon_sym_LBRACK,
    ACTIONS(327), 1,
      sym_command_stop,
    STATE(87), 3,
      sym_optionblock,
      sym_settingsblock,
      aux_sym_command_repeat1,
  [2077] = 3,
    ACTIONS(321), 1,
      anon_sym_LBRACK,
    ACTIONS(329), 1,
      sym_command_stop,
    STATE(94), 3,
      sym_optionblock,
      sym_settingsblock,
      aux_sym_command_repeat1,
  [2089] = 3,
    ACTIONS(321), 1,
      anon_sym_LBRACK,
    ACTIONS(331), 1,
      sym_command_stop,
    STATE(94), 3,
      sym_optionblock,
      sym_settingsblock,
      aux_sym_command_repeat1,
  [2101] = 3,
    ACTIONS(321), 1,
      anon_sym_LBRACK,
    ACTIONS(333), 1,
      sym_command_stop,
    STATE(89), 3,
      sym_optionblock,
      sym_settingsblock,
      aux_sym_command_repeat1,
  [2113] = 3,
    ACTIONS(321), 1,
      anon_sym_LBRACK,
    ACTIONS(335), 1,
      sym_command_stop,
    STATE(94), 3,
      sym_optionblock,
      sym_settingsblock,
      aux_sym_command_repeat1,
  [2125] = 3,
    ACTIONS(321), 1,
      anon_sym_LBRACK,
    ACTIONS(337), 1,
      sym_command_stop,
    STATE(92), 3,
      sym_optionblock,
      sym_settingsblock,
      aux_sym_command_repeat1,
  [2137] = 3,
    ACTIONS(339), 1,
      anon_sym_LBRACK,
    ACTIONS(342), 1,
      sym_command_stop,
    STATE(94), 3,
      sym_optionblock,
      sym_settingsblock,
      aux_sym_command_repeat1,
  [2149] = 4,
    ACTIONS(344), 1,
      anon_sym_RBRACK,
    ACTIONS(346), 1,
      aux_sym_keyword_token1,
    STATE(113), 1,
      sym_setting,
    STATE(121), 1,
      sym_key,
  [2162] = 4,
    ACTIONS(346), 1,
      aux_sym_keyword_token1,
    ACTIONS(348), 1,
      anon_sym_RBRACK,
    STATE(113), 1,
      sym_setting,
    STATE(121), 1,
      sym_key,
  [2175] = 3,
    ACTIONS(350), 1,
      anon_sym_COMMA,
    ACTIONS(352), 1,
      anon_sym_RBRACK,
    STATE(101), 1,
      aux_sym_settingsblock_repeat1,
  [2185] = 3,
    ACTIONS(354), 1,
      anon_sym_COMMA,
    ACTIONS(357), 1,
      anon_sym_RBRACK,
    STATE(98), 1,
      aux_sym_optionblock_repeat1,
  [2195] = 3,
    ACTIONS(346), 1,
      aux_sym_keyword_token1,
    STATE(113), 1,
      sym_setting,
    STATE(121), 1,
      sym_key,
  [2205] = 3,
    ACTIONS(359), 1,
      anon_sym_COMMA,
    ACTIONS(362), 1,
      anon_sym_RBRACK,
    STATE(100), 1,
      aux_sym_settingsblock_repeat1,
  [2215] = 3,
    ACTIONS(344), 1,
      anon_sym_RBRACK,
    ACTIONS(364), 1,
      anon_sym_COMMA,
    STATE(100), 1,
      aux_sym_settingsblock_repeat1,
  [2225] = 2,
    ACTIONS(368), 1,
      anon_sym_EQ,
    ACTIONS(366), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2233] = 3,
    ACTIONS(370), 1,
      anon_sym_COMMA,
    ACTIONS(372), 1,
      anon_sym_RBRACK,
    STATE(98), 1,
      aux_sym_optionblock_repeat1,
  [2243] = 3,
    ACTIONS(374), 1,
      anon_sym_COMMA,
    ACTIONS(376), 1,
      anon_sym_RBRACK,
    STATE(103), 1,
      aux_sym_optionblock_repeat1,
  [2253] = 3,
    ACTIONS(372), 1,
      anon_sym_RBRACK,
    ACTIONS(378), 1,
      aux_sym_keyword_token1,
    STATE(111), 1,
      sym_keyword,
  [2263] = 3,
    ACTIONS(378), 1,
      aux_sym_keyword_token1,
    ACTIONS(380), 1,
      anon_sym_RBRACK,
    STATE(111), 1,
      sym_keyword,
  [2273] = 1,
    ACTIONS(382), 2,
      sym_command_stop,
      anon_sym_LBRACK,
  [2278] = 1,
    ACTIONS(384), 2,
      sym_command_stop,
      anon_sym_LBRACK,
  [2283] = 1,
    ACTIONS(386), 2,
      sym_command_stop,
      anon_sym_LBRACK,
  [2288] = 1,
    ACTIONS(366), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2293] = 1,
    ACTIONS(357), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2298] = 1,
    ACTIONS(388), 2,
      sym_command_stop,
      anon_sym_LBRACK,
  [2303] = 1,
    ACTIONS(362), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2308] = 1,
    ACTIONS(384), 2,
      sym_command_stop,
      anon_sym_LBRACK,
  [2313] = 1,
    ACTIONS(390), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2318] = 1,
    ACTIONS(392), 2,
      sym_command_stop,
      anon_sym_LBRACK,
  [2323] = 2,
    ACTIONS(378), 1,
      aux_sym_keyword_token1,
    STATE(111), 1,
      sym_keyword,
  [2330] = 1,
    ACTIONS(394), 2,
      sym_command_stop,
      anon_sym_LBRACK,
  [2335] = 1,
    ACTIONS(396), 2,
      sym_command_stop,
      anon_sym_LBRACK,
  [2340] = 1,
    ACTIONS(398), 1,
      ts_builtin_sym_end,
  [2344] = 1,
    ACTIONS(400), 1,
      anon_sym_EQ,
  [2348] = 1,
    ACTIONS(402), 1,
      anon_sym_RBRACK,
  [2352] = 1,
    ACTIONS(368), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 48,
  [SMALL_STATE(4)] = 96,
  [SMALL_STATE(5)] = 144,
  [SMALL_STATE(6)] = 192,
  [SMALL_STATE(7)] = 240,
  [SMALL_STATE(8)] = 288,
  [SMALL_STATE(9)] = 336,
  [SMALL_STATE(10)] = 383,
  [SMALL_STATE(11)] = 430,
  [SMALL_STATE(12)] = 477,
  [SMALL_STATE(13)] = 524,
  [SMALL_STATE(14)] = 571,
  [SMALL_STATE(15)] = 618,
  [SMALL_STATE(16)] = 665,
  [SMALL_STATE(17)] = 712,
  [SMALL_STATE(18)] = 759,
  [SMALL_STATE(19)] = 789,
  [SMALL_STATE(20)] = 821,
  [SMALL_STATE(21)] = 840,
  [SMALL_STATE(22)] = 869,
  [SMALL_STATE(23)] = 888,
  [SMALL_STATE(24)] = 907,
  [SMALL_STATE(25)] = 926,
  [SMALL_STATE(26)] = 945,
  [SMALL_STATE(27)] = 964,
  [SMALL_STATE(28)] = 983,
  [SMALL_STATE(29)] = 1002,
  [SMALL_STATE(30)] = 1021,
  [SMALL_STATE(31)] = 1040,
  [SMALL_STATE(32)] = 1059,
  [SMALL_STATE(33)] = 1078,
  [SMALL_STATE(34)] = 1098,
  [SMALL_STATE(35)] = 1118,
  [SMALL_STATE(36)] = 1136,
  [SMALL_STATE(37)] = 1156,
  [SMALL_STATE(38)] = 1176,
  [SMALL_STATE(39)] = 1196,
  [SMALL_STATE(40)] = 1216,
  [SMALL_STATE(41)] = 1236,
  [SMALL_STATE(42)] = 1256,
  [SMALL_STATE(43)] = 1276,
  [SMALL_STATE(44)] = 1296,
  [SMALL_STATE(45)] = 1316,
  [SMALL_STATE(46)] = 1344,
  [SMALL_STATE(47)] = 1362,
  [SMALL_STATE(48)] = 1382,
  [SMALL_STATE(49)] = 1400,
  [SMALL_STATE(50)] = 1418,
  [SMALL_STATE(51)] = 1436,
  [SMALL_STATE(52)] = 1454,
  [SMALL_STATE(53)] = 1472,
  [SMALL_STATE(54)] = 1490,
  [SMALL_STATE(55)] = 1508,
  [SMALL_STATE(56)] = 1526,
  [SMALL_STATE(57)] = 1544,
  [SMALL_STATE(58)] = 1562,
  [SMALL_STATE(59)] = 1590,
  [SMALL_STATE(60)] = 1610,
  [SMALL_STATE(61)] = 1630,
  [SMALL_STATE(62)] = 1650,
  [SMALL_STATE(63)] = 1670,
  [SMALL_STATE(64)] = 1687,
  [SMALL_STATE(65)] = 1711,
  [SMALL_STATE(66)] = 1724,
  [SMALL_STATE(67)] = 1737,
  [SMALL_STATE(68)] = 1750,
  [SMALL_STATE(69)] = 1763,
  [SMALL_STATE(70)] = 1786,
  [SMALL_STATE(71)] = 1799,
  [SMALL_STATE(72)] = 1812,
  [SMALL_STATE(73)] = 1835,
  [SMALL_STATE(74)] = 1848,
  [SMALL_STATE(75)] = 1871,
  [SMALL_STATE(76)] = 1894,
  [SMALL_STATE(77)] = 1917,
  [SMALL_STATE(78)] = 1937,
  [SMALL_STATE(79)] = 1957,
  [SMALL_STATE(80)] = 1977,
  [SMALL_STATE(81)] = 1986,
  [SMALL_STATE(82)] = 1995,
  [SMALL_STATE(83)] = 2004,
  [SMALL_STATE(84)] = 2013,
  [SMALL_STATE(85)] = 2032,
  [SMALL_STATE(86)] = 2041,
  [SMALL_STATE(87)] = 2053,
  [SMALL_STATE(88)] = 2065,
  [SMALL_STATE(89)] = 2077,
  [SMALL_STATE(90)] = 2089,
  [SMALL_STATE(91)] = 2101,
  [SMALL_STATE(92)] = 2113,
  [SMALL_STATE(93)] = 2125,
  [SMALL_STATE(94)] = 2137,
  [SMALL_STATE(95)] = 2149,
  [SMALL_STATE(96)] = 2162,
  [SMALL_STATE(97)] = 2175,
  [SMALL_STATE(98)] = 2185,
  [SMALL_STATE(99)] = 2195,
  [SMALL_STATE(100)] = 2205,
  [SMALL_STATE(101)] = 2215,
  [SMALL_STATE(102)] = 2225,
  [SMALL_STATE(103)] = 2233,
  [SMALL_STATE(104)] = 2243,
  [SMALL_STATE(105)] = 2253,
  [SMALL_STATE(106)] = 2263,
  [SMALL_STATE(107)] = 2273,
  [SMALL_STATE(108)] = 2278,
  [SMALL_STATE(109)] = 2283,
  [SMALL_STATE(110)] = 2288,
  [SMALL_STATE(111)] = 2293,
  [SMALL_STATE(112)] = 2298,
  [SMALL_STATE(113)] = 2303,
  [SMALL_STATE(114)] = 2308,
  [SMALL_STATE(115)] = 2313,
  [SMALL_STATE(116)] = 2318,
  [SMALL_STATE(117)] = 2323,
  [SMALL_STATE(118)] = 2330,
  [SMALL_STATE(119)] = 2335,
  [SMALL_STATE(120)] = 2340,
  [SMALL_STATE(121)] = 2344,
  [SMALL_STATE(122)] = 2348,
  [SMALL_STATE(123)] = 2352,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(30),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(29),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(31),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(79),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(4),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(62),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(12),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(2),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(35),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(48),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(51),
  [106] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(78),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(6),
  [112] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(60),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(16),
  [118] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(10),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2),
  [135] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(40),
  [138] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(41),
  [141] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(34),
  [144] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(77),
  [147] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(3),
  [150] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(61),
  [153] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(11),
  [156] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2), SHIFT_REPEAT(14),
  [159] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [167] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2), SHIFT_REPEAT(66),
  [170] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2), SHIFT_REPEAT(58),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2),
  [175] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2), SHIFT_REPEAT(59),
  [178] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2), SHIFT_REPEAT(18),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_setting, 2),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escaped, 2),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1),
  [195] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 4),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_group, 3),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 3),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_group, 3),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_math, 3),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command_group, 2),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_group, 2),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_main_stop, 1),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_main_start, 1),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escapechar, 1),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_group, 3),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_brace_group, 2),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escapechar, 1),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 4),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escaped, 2),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_main_start, 1),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_main_stop, 1),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command_group, 2),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_math, 3),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 3),
  [241] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_brace_group, 3),
  [245] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [267] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_math_group_repeat1, 2), SHIFT_REPEAT(85),
  [270] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_math_group_repeat1, 2),
  [272] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_math_group_repeat1, 2), SHIFT_REPEAT(76),
  [275] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_math_group_repeat1, 2), SHIFT_REPEAT(63),
  [278] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_math_group_repeat1, 2), SHIFT_REPEAT(64),
  [281] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value_brace_group, 3),
  [283] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [285] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [287] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [289] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [291] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [293] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value_brace_group, 2),
  [295] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [297] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [299] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [301] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [303] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [305] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [307] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [309] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [311] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_group, 3),
  [313] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_math_group, 2),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [339] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(84),
  [342] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [354] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_optionblock_repeat1, 2), SHIFT_REPEAT(117),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_optionblock_repeat1, 2),
  [359] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_settingsblock_repeat1, 2), SHIFT_REPEAT(99),
  [362] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_settingsblock_repeat1, 2),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [366] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1),
  [368] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 1),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [382] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optionblock, 3),
  [384] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_settingsblock, 3),
  [386] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_settingsblock, 4),
  [388] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_settingsblock, 2),
  [390] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting, 3),
  [392] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optionblock, 5),
  [394] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_settingsblock, 5),
  [396] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optionblock, 4),
  [398] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_context_external_scanner_create(void);
void tree_sitter_context_external_scanner_destroy(void *);
bool tree_sitter_context_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_context_external_scanner_serialize(void *, char *);
void tree_sitter_context_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_context(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_context_external_scanner_create,
      tree_sitter_context_external_scanner_destroy,
      tree_sitter_context_external_scanner_scan,
      tree_sitter_context_external_scanner_serialize,
      tree_sitter_context_external_scanner_deserialize,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
